### ISSUE TITLE
Build completed but still get a failed email

### ISSUE THREAD

**Issue by BlairLee** [readthedocs/readthedocs.org#7645] opened 2020-11-05 19:43 UTC
## Details

* Read the Docs project URL: https://datasetinsights.readthedocs.io/en/latest/
* Build URL (if applicable): https://readthedocs.org/projects/datasetinsights/builds/12265546/

## Expected Result
Build completed with no error email. 

## Actual Result
Build completed. However, I still got the failed email from readthedocs.org.

*A description of what actually happened*
I checked my readthedocs log, it says build completed and it shows my build is passed. However, I got a failed email:
<img width="595" alt="Screen Shot 2020-11-05 at 11 41 54 AM" src="https://user-images.githubusercontent.com/22140633/98288727-21d52080-1f5c-11eb-8b94-6f28a4adffbe.png">

Can someone tell me what's going on?

**Comment by stsewd** [comment] 2020-11-05 21:08
Thanks for reporting, this is a duplicate of https://github.com/readthedocs/readthedocs.org/issues/7627

**Closed by stsewd** 2020-11-05 21:08 UTC
