### ISSUE TITLE
Build error with build id #10539114 + many more failures

### ISSUE THREAD

**Issue by dhalbert** [readthedocs/readthedocs.org#6730] opened 2020-03-03 00:10 UTC
_All_ of our builds https://readthedocs.org/projects/circuitpython/builds/ having been failing for about four weeks now, though we only noticed today (should have looked harder). I found the "reset build environment button" while looking at some older builds, but clicking that didn't help.

The `circuitpython` project has many subprojects, but those are building OK.

## Details:

* Project URL: https://readthedocs.org/projects/CircuitPython/
* Build URL(if applicable): https://readthedocs.org/projects/circuitpython/builds/10539114/
* Read the Docs username(if applicable): dhalbert

## Expected Result

Should have built or failed with a formatting error.

## Actual Result

```
Error
There was a problem with Read the Docs while building your documentation. Please try again later. However, if this problem persists, please report this to us with your build id (10539114).
```

Tagging @tannewt @kattni @sommersoft  (co-maintainers).

**Comment by ericholscher** [comment] 2020-03-03 21:09
This is caused by a timeout of our subprojects API, which you might have guessed. I will get a fix in for this in the next day or two.

**Comment by ericholscher** [comment] 2020-03-04 19:33
The fix for this should now be deployed, and we have a working build: https://readthedocs.org/projects/circuitpython/builds/10552282/ -- sorry about this.

**Comment by ericholscher** [comment] 2020-03-04 19:34
Of note, the current workaround is the `subprojects` list in your actual HTML build is empty. We update this via the API in production, so hopefully it shouldn't be an issue.

**Comment by tannewt** [comment] 2020-03-04 22:24
Thanks @ericholscher ! Totally fine that the subproject list is empty. Each repo has links directly to the subproject anyway.

**Comment by stsewd** [comment] 2020-03-05 15:56
Looks this is solved, we are tracking the real problem in https://github.com/readthedocs/readthedocs.org/issues/6712

**Closed by stsewd** 2020-03-05 15:56 UTC
Labels: Support
