### ISSUE TITLE
Do not show the older versions!

### ISSUE THREAD

**Issue by mushroomfire** [readthedocs/readthedocs.org#10855] opened 2023-10-20 14:06 UTC
## Details

* Read the Docs project URL: https://readthedocs.org/projects/mdapy/
* Build URL (if applicable): https://readthedocs.org/projects/mdapy/builds/22293087/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/mushroomfire/

## Expected Result

*I hope I can access the previous version. Please tell me how to do, thanks a lot.*

## Actual Result

*After i update the readthedocs.yaml to version 2, the site do not show the older version any more. I can not press the button to change the version, only the latest version is presented.*

![image](https://github.com/readthedocs/readthedocs.org/assets/77276727/ee979dba-5ccb-4a35-81f5-1dea25d31373)

**Comment by humitos** [comment] 2023-10-23 10:07
Looks like a duplicate of https://github.com/readthedocs/readthedocs.org/issues/10841. Please, follow the instructions from there and let us know if it works.

**Closed by humitos** 2023-10-23 10:07 UTC

**Comment by mushroomfire** [comment] 2023-10-23 13:57
Everything works well now as suggested. Thanks a lot. @humitos
