### ISSUE TITLE
Execute shell scripts before build

### ISSUE THREAD

**Issue by belerico** [readthedocs/readthedocs.org#6929] opened 2020-04-18 14:23 UTC
## Details
It would be nice to permit users to run shell scripts before a build, e.g. I need to use `sed` linux command to substitute a path in a file before the building process, so that a relative image can be properly load 

## Expected Result

Maybe a new section in the .yml called `script` or `before-script` could be added, like the Travis or GitLab ones:
```yml
version: 2

before-script:
  - sed -i "s/path/new_path/1" file.md  # or directly call sh substitute.sh

sphinx:
  builder: html
  fail_on_warning: false
  configuration: docs/source/conf.py

formats: all

python:
  version: 3.7
  install:
    - requirements: docs/requirements.txt
    - method: setuptools
      path: .
```

## Actual Result

I think I can come up with a Pythonic solution involving running a function in the sphinx conf.py, but there maybe would be cases in which the python solution could nont be affordable

**Comment by Daltz333** [comment] 2020-04-20 03:40
The above solution could also solve https://github.com/readthedocs/readthedocs.org/issues/6919 if implemented

**Comment by stsewd** [comment] 2020-04-20 14:39
Duplicate of https://github.com/readthedocs/readthedocs.org/issues/6662

**Closed by stsewd** 2020-04-20 14:39 UTC

**Comment by humitos** [comment] 2022-04-11 07:46
Hi @belerico! You can now achieve your goal by using `build.jobs`. Read the documentation at https://docs.readthedocs.io/en/stable/config-file/v2.html#build-jobs
