### ISSUE TITLE
Download of multi-page HTML?

### ISSUE THREAD

**Issue by takluyver** [readthedocs/readthedocs.org#3242] opened 2017-11-10 16:33 UTC
The download HTML option offers a zip file containing a single HTML file with the full contents of the docs. Is there a way to get a zip file with multiple independent pages (the same structure that RTD serves)? The single-page version is a bit unwieldy for larger documentation. Python's own Sphinx docs are [available for download](https://docs.python.org/3/download.html) as multi-page HTML.

It sounds from the description like PR #675 switched HTML downloads away from multi-page, but don't know if I've understood that correctly.

**Comment by pwab** [comment] 2018-01-08 22:59
The [Godot](https://github.com/godotengine/godot) [docs](http://docs.godotengine.org/en/latest/) have the same problem. When [downloading the html export](http://readthedocs.org/projects/godot/downloads/htmlzip/latest/) you receive an index file consisting of 68000 lines at a size of 6.5 mb.

As stated on [stackoverflow](https://stackoverflow.com/questions/32771287/download-html-as-separate-pages) _"there's currently no setting to change that"_ (2015). Did that change in between?

Is this somehow related to the [DOCUMENTATION_CHOICES](https://github.com/rtfd/readthedocs.org/blob/32e3073af0886fb6b3e02164a40a4c4ef9d666da/readthedocs/projects/constants.py#L28-L29) constant?
https://github.com/rtfd/readthedocs.org/blob/32e3073af0886fb6b3e02164a40a4c4ef9d666da/readthedocs/projects/constants.py#L28-L29

Regarding the helptext at ...
https://github.com/rtfd/readthedocs.org/blob/9f4519b07873ebb76c7feb0e078fa1dfc085465f/readthedocs/projects/models.py#L134-L137

... it should be possible to use the [DirectoryHTMLBuilder](http://www.sphinx-doc.org/en/stable/builders.html#sphinx.builders.html.DirectoryHTMLBuilder). But how to configure the `conf.py` in the right way?

**Comment by stsewd** [comment] 2018-11-28 00:48
There isn't an option to download the docs as no-singlehtml, and yeah, this looks like a good feature for the rtd configuration file.

**Comment by stsewd** [comment] 2018-11-28 00:51
Just linking to another opinion why this would be important https://github.com/rtfd/readthedocs.org/issues/4190

**Comment by akien-mga** [comment] 2020-03-16 12:22
Still quite interested in having this feature, we get lots of requests for offline docs for Godot and with such a massive project (750K words today as per `wc -w $(find -name "*.rst")`), the singlehtml target simply isn't practical (and EPUB/PDF hardly either).

Until then:

> ... it should be possible to use the [StandaloneHTMLBuilder](http://www.sphinx-doc.org/en/stable/builders.html#sphinx.builders.html.StandaloneHTMLBuilder). But how to configure the `conf.py` in the right way?

Would there be a workaround we can code to upload a self-built StandaloneHTML Zip and have it exposed in the ReadTheDocs UI?

**Comment by stsewd** [comment] 2020-03-16 17:57
Sorry, no work around currently

**Comment by Daltz333** [comment] 2022-01-18 04:12
Another bump on this? Our docs consist of 1000+ pages and can crash some browsers (weak machines with 2GB ram) when loading the singlepage version...

**Comment by TheTripleV** [comment] 2022-01-24 02:20
RTD builds the local media with the builder `readthedocssinglehtmllocalmedia` which is defined at https://github.com/readthedocs/readthedocs-sphinx-ext/blob/master/readthedocs_ext/readthedocs.py#L369-L378.
To change the behavior of this builder, a new builder with the same name can be registered with Sphinx overriding the one RTD defines.

https://github.com/wpilibsuite/frc-docs/commit/dc238f04e23a656be7ef22a22b905c8e10040020 is an example of this.

Creating a local extension with
```py
from sphinx.builders.html import StandaloneHTMLBuilder

class ReadtheDocsBuilderLocalMedia(StandaloneHTMLBuilder):
    name = "readthedocssinglehtmllocalmedia"

def setup(app):
    app.add_builder(ReadtheDocsBuilderLocalMedia, override=True)
```
changes the zip to build using `StandaloneHTMLBuilder`. As long as the builder's name is `readthedocssinglehtmllocalmedia`, it will override.

**Comment by astrojuanlu** [comment] 2022-01-24 09:52
Thanks for sharing your solution @TheTripleV !

**Comment by humitos** [comment] 2023-01-31 13:11
Hello 👋🏼 We standardized the output paths for all the formats that Read the Docs supports in https://github.com/readthedocs/readthedocs.org/pull/9888. This allow people to output, for example, a HTMLZip under `_readthedocs/htmlzip/<project-slug>.zip` to be recognized by Read the Docs and expose it as a downloadable content ([docs.readthedocs.io/en/stable/downloadable-documentation.html](https://docs.readthedocs.io/en/stable/downloadable-documentation.html)) 💯 

There is no more need to override a Sphinx builder as mentioned in https://github.com/readthedocs/readthedocs.org/issues/3242#issuecomment-1019653037 anymore. You can build the `.zip` file as you wish (e.g. using [Zunlder](https://github.com/AdrianVollmer/Zundler/)) and just outputting the resulting file at `_readthedocs/htmlzip/<project-slug>.zip`

I created an example that builds a single HTML file using `StandaloneHTMLBuilder` and zips it to be considered as "Downloadable documentation" by Read the Docs and expose it in the flyout:
* Documentation: https://test-builds.readthedocs.io/en/sphinx-multipage-html/
* Repository: https://github.com/readthedocs/test-builds/tree/sphinx-multipage-html

I'm closing this issue since I think the problem is solved. However, feel free to share any feedback here or re-open if you consider.

**Closed by humitos** 2023-01-31 13:11 UTC
Labels: Feature, Needed: design decision

**Comment by takluyver** [comment] 2023-01-31 13:32
I think my initial request back in 2017 was more for this to be available for any docs - I was wanting to download multi-page docs for projects that I don't control. But most of the other comments on this issue seem to be from people who want to enable it for their own projects, so it's probably reasonable to close it.
