### ISSUE TITLE
Development Installation: Document Build Failed

### ISSUE THREAD

**Issue by wujingwen97** [readthedocs/readthedocs.org#8973] opened 2022-02-26 03:48 UTC
## Details

ENV:
    OS: CentOS 7.5(wsl2)
    docker: 20.10.8
    docker-compose: 1.29.2
    python: 3.8.9
    pip: 22.0.3

Version:
    readthedocs: I tried the latest, 5.22.0 and 5.21.0

## Expected Result

I successfully installed readthedocs following "https://dev.readthedocs.io/en/latest/install.html", but when I tried to build the document, it failed.

## Actual Result

The Error :

Command git clone --no-single-branch --depth 50 https://github.com/rtfd/readthedocs.org . failed: OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: chdir to cwd ("/usr/src/app/checkouts/readthedocs.org/user_builds/read-the-docs/checkouts/latest") set in config.json failed: no such file or directory: unknown

Command git clone --no-single-branch --depth 50 https://github.com/rtfd/readthedocs.org . failed: OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: chdir to cwd ("/usr/src/app/checkouts/readthedocs.org/user_builds/read-the-docs/checkouts/0.2.1") set in config.json failed: no such file or directory: unknown

**Comment by humitos** [comment] 2022-03-15 12:04
Hi @wujingwen97! I don't have a good way to try to reproduce this issue because I don't use WSL2. Most of our team uses Linux/Mac. However, one person in our team does use WSL2 with Ubuntu and following the instructions documented did not have any issue. Can you try using Ubuntu instead of CentOS?

**Comment by ericholscher** [comment] 2022-03-25 22:57
Closing this because we don't support anything other than Ubuntu & Docker for development.

**Closed by ericholscher** 2022-03-25 22:57 UTC
Labels: Support, Needed: more information, Needed: replication
