### ISSUE TITLE
Rename slug of my project

### ISSUE THREAD

**Issue by vnmabus** [readthedocs/readthedocs.org#5836] opened 2019-06-21 09:10 UTC
Hello,

Per #5403, it seems I can ask here if I want to rename a slug.

I currently have the page https://fda.readthedocs.io/en/latest/ . However, we changed the name of our project to brand it as a scikit. Would it be possible to have the documentation in https://scikit-fda.readthedocs.io/en/latest/ ?

Ideally I would want that the old page redirects to the new one, in order not to break the Internet.

Thanks in advance

**Comment by ericholscher** [comment] 2019-06-27 22:46
Sure, we can definitely do that. I will get the redirects setup and deployed next week. 👍

**Comment by vnmabus** [comment] 2019-08-19 01:19
I am reopening this, at it is still pending.

**Comment by ericholscher** [comment] 2019-08-19 19:07
Bah, sorry for the delay here, do you still want this done?

**Comment by vnmabus** [comment] 2019-08-19 20:10
Yes, please.

**Comment by ericholscher** [comment] 2019-08-20 14:40
Just as a note, this will break all current links to the project. Hopefully in the near future we should be able to support automatic renaming & redirects, but currently it's all manual.

**Comment by ericholscher** [comment] 2019-08-20 14:41
I can probably set them up in nginx for now, but it might break in the futute

**Comment by vnmabus** [comment] 2019-08-20 14:59
> Just as a note, this will break all current links to the project. Hopefully in the near future we should be able to support automatic renaming & redirects, but currently it's all manual.

Hum, I though that it was possible to redirect the old url to the new one. I do not want to break existing links 😢.

**Comment by vnmabus** [comment] 2020-01-28 23:28
Which information is needed?

**Comment by stsewd** [comment] 2020-01-29 01:22
@vnmabus if you don't have anything like very complex settings in the admin, you can just create a new project with that name and delete the old one. But that wouldn't make a redirect for the other project.

**Comment by vnmabus** [comment] 2020-01-29 22:14
Yeah, but that is the thing... I do not want to break existing links.

**Comment by humitos** [comment] 2020-02-24 09:55
If you re-import your project under the new name, you can create an Exact redirect with `$rest` in the _old project_ pointing to the new URL. See https://docs.readthedocs.io/en/stable/user-defined-redirects.html#exact-redirects

**Comment by stsewd** [comment] 2020-02-24 15:10
@humitos those would only work on 404

**Comment by ericholscher** [comment] 2020-04-29 16:40
I'm closing this. It's a duplicate of #2267

**Closed by ericholscher** 2020-04-29 16:40 UTC
Labels: Accepted, Support
