### ISSUE TITLE
Project Build Fail

### ISSUE THREAD

**Issue by EDI-N** [readthedocs/readthedocs.org#10291] opened 2023-05-04 16:58 UTC
## Details

* Read the Docs project URL: https://readthedocs.org/projects/docs-ua/
* Build URL (if applicable): all last builds
* Read the Docs username (if applicable): https://readthedocs.org/profiles/EDI-N/

## Expected Result

All last builds falls in errors

## Actual Result

All last builds falls in errors... Less than 6 hours everything were fine ( conf.py or requirements.txt files have not been modified)
Can You help me fix config?

**Comment by stsewd** [comment] 2023-05-04 17:12
Hi, please see https://github.com/readthedocs/readthedocs.org/issues/10290#issuecomment-1535028830.

**Comment by agjohnson** [comment] 2023-05-04 21:26
Closing this as a duplicate of the bug report in #10290, feel free to follow up there if the fixes there don't help.

**Closed by agjohnson** 2023-05-04 21:26 UTC
Labels: Support
