### ISSUE TITLE
AttributeError: module 'site' has no attribute 'getsitepackages

### ISSUE THREAD

**Issue by shfarhee** [readthedocs/readthedocs.org#10185] opened 2023-03-23 16:32 UTC
I am trying to import a project from git-hub to read the doc website where rst files are working and(source code) the python code is not showing anything. Where as the same setup is working fine in my local system.
i am getting **'getsitepackages' issue (* AttributeError: module 'site' has no attribute 'getsitepackages'.** and some of the python files are showing and some isn't
ERROR- getting 'getsitepackages' issue ( AttributeError: module 'site' has no attribute 'getsitepackages'.* and some of the python files are showing and some isn't inReadthedoc .
<img width="364" alt="getsitepackage" src="https://user-images.githubusercontent.com/116381069/227271749-3141b1b5-3934-4986-90bd-64d6c993c137.PNG">
Reference Raw Doc link-https://readthedocs.org/api/v2/build/19870138.txt
Project link- https://readthedocs.org/projects/responsibleai/builds/19870138/

**Comment by stsewd** [comment] 2023-03-23 16:59
Hi there, looks like a duplicate of https://github.com/readthedocs/readthedocs.org/issues/10155? This is usually because there is a missing dependency that you have locally and not on RTD, you should be able to replicate it locally by executing the same steps from rtd in a clean environment.

**Closed by stsewd** 2023-03-23 16:59 UTC
