### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by gwilku** [readthedocs/readthedocs.org#8640] opened 2021-10-31 14:54 UTC
Hi, I'm getting a fail in docs build...

Any clues?
I tried figuring it out from similar RTD build fail issues, but it seems that this is a config on RTD side, not on mine... or - how can I change the packages that the RTD's Sphinx uses? I'm a bit lost here.

Running Sphinx v1.8.5
loading translations [en]... done
making output directory...
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 18 source files that are out of date
updating environment: 18 added, 0 changed, 0 removed
reading sources... [  5%] dodge/ram
reading sources... [ 11%] general/advanced_scan
reading sources... [ 16%] general/drl
reading sources... [ 22%] general/getting_started

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/jscan-docs/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 304, in build_main
    app.build(args.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jscan-docs/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 341, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/jscan-docs/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 347, in build_update
    len(to_build))
  File "/home/docs/checkouts/readthedocs.org/user_builds/jscan-docs/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 360, in build
    updated_docnames = set(self.read())
  File "/home/docs/checkouts/readthedocs.org/user_builds/jscan-docs/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 468, in read
    self._read_serial(docnames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jscan-docs/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 490, in _read_serial
    self.read_doc(docname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jscan-docs/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 534, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/home/docs/checkouts/readthedocs.org/user_builds/jscan-docs/envs/latest/lib/python3.7/site-packages/sphinx/io.py", line 318, in read_doc
    pub.publish()
  File "/home/docs/checkouts/readthedocs.org/user_builds/jscan-docs/envs/latest/lib/python3.7/site-packages/docutils/core.py", line 219, in publish
    self.apply_transforms()
  File "/home/docs/checkouts/readthedocs.org/user_builds/jscan-docs/envs/latest/lib/python3.7/site-packages/docutils/core.py", line 200, in apply_transforms
    self.document.transformer.apply_transforms()
  File "/home/docs/checkouts/readthedocs.org/user_builds/jscan-docs/envs/latest/lib/python3.7/site-packages/sphinx/transforms/__init__.py", line 90, in apply_transforms
    Transformer.apply_transforms(self)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jscan-docs/envs/latest/lib/python3.7/site-packages/docutils/transforms/__init__.py", line 171, in apply_transforms
    transform.apply(**kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jscan-docs/envs/latest/lib/python3.7/site-packages/sphinx/transforms/__init__.py", line 245, in apply
    apply_source_workaround(n)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jscan-docs/envs/latest/lib/python3.7/site-packages/sphinx/util/nodes.py", line 94, in apply_source_workaround
    for classifier in reversed(node.parent.traverse(nodes.classifier)):
TypeError: 'generator' object is not reversible

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/jscan-docs/envs/latest/lib/python3.7/site-packages/sphinx/util/nodes.py", line 94, in apply_source_workaround
    for classifier in reversed(node.parent.traverse(nodes.classifier)):
TypeError: 'generator' object is not reversible
The full traceback has been saved in /tmp/sphinx-err-9xc48fpk.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!

**Comment by astrojuanlu** [comment] 2021-10-31 15:58
Please share your project URL and failing build URL

**Comment by gwilku** [comment] 2021-10-31 16:08
Hi, thanks for reaching out.
The project:  https://jscan-docs.readthedocs.io/en/latest/
the build: https://readthedocs.org/projects/jscan-docs/builds/15141374/
the repo: https://github.com/gwilku/jscan-docs

**Comment by gwilku** [comment] 2021-10-31 16:15
I get the big picture, I just can;t find proper syntax nor samples / examples of the requirements.txt - seems missing in the RTD docs:  https://docs.readthedocs.io/en/stable/config-file/v2.html#requirements-file

It's mentioned, but there's no sample.
It is also not properly dcumented in the Sphinx's documentation itself: https://sphinx-rtd-tutorial.readthedocs.io/en/latest/sphinx-config.html

**Comment by astrojuanlu** [comment] 2021-10-31 16:23
Good point, thanks for the insight @gwilku. This page contains exactly what you need: https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html you will need to have the line `docutils<0.18` or `docutils==0.17.1` on your `requirements.txt`.

Closing as duplicate of #8616 , #8618.

**Closed by astrojuanlu** 2021-10-31 16:23 UTC
