### ISSUE TITLE
Builds broken with `poetry` 1.8

### ISSUE THREAD

**Issue by etianen** [readthedocs/readthedocs.org#11150] opened 2024-02-25 17:09 UTC
Following the [install dependencies with poetry](https://docs.readthedocs.io/en/stable/build-customization.html#install-dependencies-with-poetry) guide, I get the following error with `poetry` 1.8:

```
no theme named 'furo' found (missing theme.conf?)
```

However, the theme is clearly installed!

```
- Installing furo (2024.1.29)
```

Specifically installing `poetry` 1.7 with fixes the issue:

``` yaml
- pip install 'poetry~=1.7.0'
```

I don't see anything in the [`poetry` 1.8 release notes](https://python-poetry.org/history/#180---2024-02-25) to as a cause for the breakage. If you can pin down what the problem is, I'll gladly follow-up with an issue on the `poetry` issue tracker. 🙇 

## Details

* Read the Docs project URL: https://readthedocs.org/projects/logot/
* Build URL (if applicable): https://readthedocs.org/projects/logot/builds/23555282/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/etianen/

## Expected Result

The build to pass with `poetry` 1.8 👍 

## Actual Result

The build fails with `poetry` 1.8 👎

**Comment by ewjoachim** [comment] 2024-02-25 17:34
Looks like we have the same issue: https://github.com/readthedocs/readthedocs.org/issues/11149

**Comment by ewjoachim** [comment] 2024-02-25 17:36
I'm noting that 1.8.0 has been released in december, but it only started failing recently, so something changed, that is different in Poetry 1.8.0 and 1.7.0 but chances are it's not poetry itself.

**Comment by ewjoachim** [comment] 2024-02-25 17:43
I installed both poetry versions in 2 venvs and compared the pip freeze, then look at the last release date of the packages that have a different version:
- [CacheControl](https://pypi.org/project/CacheControl/#history): 2024/02/02
- [platformdirs](https://pypi.org/project/platformdirs/#history): 2024/01/31
- [poetry-core](https://pypi.org/project/poetry-core/#history): 2024/02/02
- [xattr](https://pypi.org/project/xattr/#history): 2024/02/02

Nothing seems to have been updated recently that would explain both that it works with 1.7, and that it worked with 1.8 5 days ago.

**Comment by ewjoachim** [comment] 2024-02-25 17:45
Hmpf, I completely misread. Poetry 1.8 was released 5 hours ago.

**Comment by ewjoachim** [comment] 2024-02-25 18:49
So there's https://github.com/python-poetry/poetry/issues/9025 for tracking the issue in Poetry.

So far, it seems it's a consequence of https://github.com/python-poetry/poetry/pull/8970 that makes detection of venv more strict. Because RTD doesn't expose `VIRTUAL_ENV`, Poetry doesn't consider this a virtualenv, and installs to the base Python instead of the one in the venv.

Poetry folks indicate that RTD should not advocate using `poetry config virtualenvs.create false`, it only worked because of a bug.

So what now ?
- Should we use a different technique for installing poetry deps ? (e.g. poetry export + pip install ?)
- Should we make it so that the build sets the VIRTUAL_ENV envvar as part of the yaml instructions ?
- Should the `VIRTUAL_ENV` variable be set by RTD itself for every build ?

**Comment by etianen** [comment] 2024-02-25 19:00
I'd vote for (3). I always set this when activating a venv programmatically.

**Comment by dimbleby** [comment] 2024-02-25 19:34
> Should the VIRTUAL_ENV variable be set by RTD itself for every build ?

If that means that the variable is also set at the moment that you execute `pip install poetry` - then this also is not correct.  Poetry must be in a different environment than the project under management: else installing the project dependencies can break the environment for poetry.

I do not see a solution that can avoid changing the instructions.

(This probably means that both poetry and readthedocs will be dealing with duplicate reports of this for some time to come: until fixed instructions eventually work their way through the system...)

**Comment by etianen** [comment] 2024-02-25 19:55
How about making pipx be available on runners (maybe it is already?!).

Installing poetry via pipx is how it's done in GitHub actions, and it works
like a charm!

**Comment by humitos** [comment] 2024-02-25 20:27
> How about making pipx be available on runners (maybe it is already?!).

It's not, but it can be installed via

```
python3 -m pip install --user pipx
python3 -m pipx ensurepath
```

_(from https://pipx.pypa.io/stable/#on-linux)_

If that's the best way to install and execute poetry, we can update the documentation to reflect that.

**Comment by humitos** [comment] 2024-02-25 20:37
> Poetry folks [indicate](https://github.com/python-poetry/poetry/issues/9025#issuecomment-1963025693) that RTD should not advocate using `poetry config virtualenvs.create false`

This is required because there are other Python commands executed by Read the Docs (e.g. `sphinx-build`) that need to be executed using the _current_ virtualenv where all the requirements were installed --that's why poetry and the requirements for building the documentation has to be installed in the same virtualenv.

These commands are executed by Read the Docs,

```
python -m pip install --upgrade --no-cache-dir pip setuptools              
python -m pip install --upgrade --no-cache-dir sphinx readthedocs-sphinx-ext
python -m sphinx -T -b html -d _build/doctrees -D language=en . $READTHEDOCS_OUTPUT/html
```

and these should work without any modification. Note that we cannot prepend them with `pipx run` or similar.

**Comment by etianen** [comment] 2024-02-25 20:40
Installing via pipx is one of the recommended ways to install poetry:

https://python-poetry.org/docs/

(Sorry I can't link more specifically on mobile, docs seem to be a SPA.)

So a pipx installation coupled with the additional venv environmental
variable would work.

It would be lovely to have pipx already installed. It's very mainstream and
opens the door to installing all sorts of CLI tools without polluting the
main venv. GHA comes with it installed, for example.

**Comment by humitos** [comment] 2024-02-25 20:46
I'm happy to update our documentation with a different solution if you have one that does work for this particular use case.

> It would be lovely to have pipx already installed

Unfortunately, we can't do this in the short term at least; but it's easy to install it as I showed before.

**Comment by etianen** [comment] 2024-02-25 20:51
Would it be possible to set that extra env var? That's all that's needed
for poetry to detect the venv correctly. And I think it makes the venv
activation for correct for other tools that might rely on it.

Then the docs can be updated to install poetry via pipx, and lose the
poetry config call.

**Comment by ewjoachim** [comment] 2024-02-25 21:42
> BTW, do you know what's the bug that they fixed that changed this behavior? Their documentation for `virtualenvs.create` ([python-poetry.org/docs/configuration#virtualenvscreate](https://python-poetry.org/docs/configuration#virtualenvscreate)) still says that it should work in the way we expect to work: don't create a new virtualenv when installing dependencies --but it seems it doesn't work like that anymore.

Not really. They don't create a virtualenv, so it works as intended. The behaviour is "if we're in a venv, use the venv. If not, install to the system python."
Because RTD doesn't set VIRTUAL_ENV (as `virtualenv` and `python -m venv` do when using `source bin/activate`), they don't detect they're in a virtualenv, so they don't do that. I suspect that they used to do something along the lines of `python -m pip ...` and they now do `$(readlink python) -m pip ...` (if they don't detect a venv). I don't think it contradicts the doc.

**Comment by ewjoachim** [comment] 2024-02-25 21:56
For the record, I got a running build in RTD with:
```yaml
version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    post_create_environment:
      - python -m pip install poetry
    post_install:
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH python -m poetry install --with docs
```
I'll open a PR for this to become "the way". When we can improve this, we will.

**Closed** 2024-02-27 09:01 UTC
Labels: Needed: design decision
