### ISSUE TITLE
IPYNB format document can not show in  the right way

### ISSUE THREAD

**Issue by BAOOOOOM** [readthedocs/readthedocs.org#8408] opened 2021-08-14 09:30 UTC
## Details

Please read the Docs project URL: https://edunlp.readthedocs.io/en/docs_dev/build/blitz/sif/sif.html

## Expected Result

When I click the picture, the link should show in ipynb format(just like stable editon URL:https://edunlp.readthedocs.io/en/stable/build/blitz/sif/sif.html ) .
![image](https://user-images.githubusercontent.com/82091145/129441453-2dface88-a8c4-4db4-b06d-7544b019a580.png)

## Actual Result

After I update some documents(In docs_dev editon URL:https://edunlp.readthedocs.io/en/docs_dev/build/blitz/sif/sif.html ), it show in txt format, just like it:
![image](https://user-images.githubusercontent.com/82091145/129441478-fbd22eb4-3ebb-413b-9751-ef88a791f30c.png)

**Comment by astrojuanlu** [comment] 2021-08-14 09:42
Hello @BAOOOOOM , are you able to build your documentation locally? If so, what result do you get? This should clarify if the problem is on the Read the Docs side or on your Sphinx configuration.

If I'm not mistaken, you're using nbsphinx to load your notebooks, including https://github.com/bigdata-ustc/EduNLP/blob/docs_dev/examples/sif/sif.ipynb, is that right? Are there other notebook files that show correctly?

**Comment by BAOOOOOM** [comment] 2021-08-14 11:09
If I build the documentation locally, it shows without mistake.  I use nbsphinx to load the notebooks, but others don't go bad. Thank you!

**Comment by astrojuanlu** [comment] 2021-08-16 11:32
@BAOOOOOM I just cloned your `docs_dev` branch and obtained the exact same problem, therefore it is not a Read the Docs issue.

Moreover, the `master` branch is also broken online: https://edunlp.readthedocs.io/en/latest/build/blitz/sif/sif.html

Therefore, initially one would think that something broke between `31eded67` (your `stable` version`) and `master`. However, I tried rebuilding `31eded67` locally and it also shows an error. Even older commits appear broken as well.

At this point, I think it will be more productive if you debug the issue locally a bit more and try to narrow down what the problem is.

**Comment by BAOOOOOM** [comment] 2021-08-18 02:58
> @BAOOOOOM I just cloned your `docs_dev` branch and obtained the exact same problem, therefore it is not a Read the Docs issue.
> 
> Moreover, the `master` branch is also broken online: https://edunlp.readthedocs.io/en/latest/build/blitz/sif/sif.html
> 
> Therefore, initially one would think that something broke between `31eded67` (your `stable` version`) and `master`. However, I tried rebuilding `31eded67` locally and it also shows an error. Even older commits appear broken as well.
> 
> At this point, I think it will be more productive if you debug the issue locally a bit more and try to narrow down what the problem is.

Thank you very much.  The promble seems to have appeared with nbsphinx 0.8.7. And it has a method to address the promble in https://github.com/spatialaudio/nbsphinx/issues/595

**Comment by astrojuanlu** [comment] 2021-08-18 05:07
I see, thanks for the update! Closing

**Closed by astrojuanlu** 2021-08-18 05:07 UTC
Labels: Support
