### ISSUE TITLE
404 in search after pages were moved

### ISSUE THREAD

**Issue by Flid** [readthedocs/readthedocs.org#6320] opened 2019-10-22 12:41 UTC
## Details
* Read the Docs project URL: https://kedro.readthedocs.io/

When searching for something, for example, [databricks](https://kedro.readthedocs.io/en/latest/search.html?q=databricks&check_keywords=yes&area=default), there will be two entries in the output, but one of them leads to a 404 page. 
The broken link is `https://kedro.readthedocs.io/en/latest/04_user_guide/11_working_with_databricks.html`
The working one is `https://kedro.readthedocs.io/en/latest/04_user_guide/12_working_with_databricks.html` - note `11` vs `12`. We've renamed the MD file and rebuilt the docs, but the old file is still in the search index. I can probably manually redirect pages, but it seems to be a workaround rather than a real fix.

The issue looks very similar to https://github.com/readthedocs/readthedocs.org/issues/5668, but the issue persists for us.

## Expected Result
All pages returned from the search are accessible.

## Actual Result
`https://kedro.readthedocs.io/en/latest/04_user_guide/11_working_with_databricks.html` is showed in the results, but it's 404.

**Comment by stsewd** [comment] 2019-10-22 15:20
Closing as duplicate of https://github.com/readthedocs/readthedocs.org/issues/6069

**Closed by stsewd** 2019-10-22 15:20 UTC

**Comment by Flid** [comment] 2019-10-28 10:10
@stsewd And still the issue is not fixed. We've tried wiping out the branch, rebuilding it etc - still we see a bunch of 404 errors around, nothing has changed. Can you reopen the issue please?

**Comment by stsewd** [comment] 2019-10-28 17:43
@Flid it's fixed, but the change isn't deployed yet

**Comment by Flid** [comment] 2019-10-29 10:37
Oh riiiight. Thank you! Just found the changelog page, we'll keep an eye on it.

**Comment by jcampbell** [comment] 2019-11-12 12:16
@stsewd : this seems to affect enough sites that it's worth deploying the fix. Any chance you'd be willing to push the new release including the fix so we can also benefit?

**Comment by stsewd** [comment] 2019-11-12 14:13
@jcampbell sorry you are having this problem, we are a small team so it makes it hard to deploy that often, but a deploy is planned for today, hope it goes smoothly

**Comment by jcampbell** [comment] 2019-11-12 14:15
Thank you so much for the update--we *really* appreciate your great work!

**Comment by stsewd** [comment] 2019-11-12 19:31
@jcampbell @Flid the fix is deployed now, you need to trigger a new build to refresh the search index

**Comment by jcampbell** [comment] 2019-11-12 20:14
I've wiped and rebuilt, and can confirm our search index is clean now. Thank you again, @stsewd !!
