### ISSUE TITLE
Build: expose location of virtualenv

### ISSUE THREAD

**Issue by davidism** [readthedocs/readthedocs.org#9629] opened 2022-09-28 13:23 UTC
I'm using the [PDM](https://pdm.fming.dev/latest/) dependency management tool, moving away from `requirements.txt` files. If PDM does not detect an active virtualenv, or is not told about the location of a virtualenv, it will create one and install packages there.

Read the Docs does not activate or expose the path to the virtualenv it creates. It seems that `which python` does report the virtualenv python despite that, so a hack is used to get the path and tell PDM about it. https://github.com/pdm-project/pdm/discussions/1365#discussioncomment-3581356

```
VIRTUAL_ENV=$(dirname $(dirname $(which python))) ~/.local/bin/pdm sync -dG docs
```

It would be helpful if Read the Docs made the virtualenv easier to find. You could set `VIRTUAL_ENV`, or maybe `RTD_VIRTUAL_ENV` if you don't want to affect other tools by default. Alternatively, activate it.

* Read the Docs project URL: https://readthedocs.org/projects/flask-sqlalchemy/
* Build URL (if applicable): https://readthedocs.org/projects/flask-sqlalchemy/builds/18192947/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/davidism/

**Comment by humitos** [comment] 2022-09-28 16:18
Hi @davidism! I don't have experience working with PDM, so maybe what I'm going to suggest makes no sense 😄 

However, for Poetry users that have a similar situation where the "feature of auto-creation of the virtualenv interferes with Read the Docs default build workflow" we documented a workaround for that at https://docs.readthedocs.io/en/latest/build-customization.html#install-dependencies-with-poetry. I saw that PDM does support something similar https://pdm.fming.dev/latest/usage/venv/#disable-virtualenv-mode

That solution/workaround does work for your case?

**Comment by davidism** [comment] 2022-09-28 16:20
In PDM, disabling virtualenv support means enable the old `__pypackages__` PEP, which won't solve the issue either. There is no way to completely disable venv support as far as I know. Maybe @frostming can say more.

**Comment by davidism** [comment] 2022-10-20 16:50
@davidfischer @ericholscher This is the virtualenv feature I was talking about yesterday.

**Comment by ericholscher** [comment] 2022-10-24 21:50
Gotcha, I was going to suggest something like `VIRTUAL_ENV=$(dirname $(dirname $(which python)))` as a workaround, since we do run via the Python executable. I agree that adding an ENV for this would be useful, but that's not the worst workaround for now.

**Comment by davidism** [comment] 2023-01-09 19:12
I'm planning to switch Flask, Click, etc. to PDM soon. It would be nice to be able to directly reference the virtualenv location. What's the status of work on this?

**Comment by ericholscher** [comment] 2023-01-10 21:42
@davidism I will add this to our upcoming sprint so we can take a look at it. I think it's reasonable to add it to the environment, and won't be complex, but mostly just need to do the PR 👍

**Comment by davidism** [comment] 2023-02-01 16:52
@frostming does this look correct?

**Comment by frostming** [comment] 2023-02-02 00:57
LGTM

**Comment by davidism** [comment] 2023-02-02 18:04
Will you close this once it's deployed? Or is it ready for me to test?

**Comment by ericholscher** [comment] 2023-02-02 18:05
@davidism It should go out in our deploy next week on Tuesday. This issue will likely get closed once the issue is merged, but Tuesday is the day :)

**Closed** 2023-02-07 10:02 UTC
Labels: Feature, Accepted

**Comment by humitos** [comment] 2023-02-07 16:49
@davidism @frostming This is already deployed. You should be able to make usage of the variable `READTHEDOCS_VIRTUALENV_PATH` now from your build commands. Let me know if this works as you expected 👍🏼

**Comment by davidism** [comment] 2023-02-08 19:45
Looks like it worked: https://readthedocs.org/projects/flask-sqlalchemy/builds/19424647/
