### ISSUE TITLE
Private versions are not accessible even by admins

### ISSUE THREAD

**Issue by nadiaya** [readthedocs/readthedocs.org#5253] opened 2019-02-07 21:45 UTC
## Details
Private documentation version is not accessible even by admins: 'Permission Denied' returned to everyone.

* Read the Docs project URL: https://readthedocs.org/projects/sagemaker/
* Build URL (if applicable): N/A
* Read the Docs username (if applicable): awsml

## Expected Result

After making 'latest' version to be private, according to https://docs.readthedocs.io/en/latest/privacy.html#private, we should be able to view the documentation for this version when logged in an admin account for this project.

## Actual Result

When going to https://sagemaker.readthedocs.io/en/latest/ getting 'Permission Denied' even when logged in an admin account.

**Comment by stsewd** [comment] 2019-02-17 19:24
Are you still having this problem? Also, I only see one maintainer in the project (awsml).

And we are about to remove/deprecate the privacy levels https://github.com/rtfd/readthedocs.org/issues/2663

**Comment by taradinoc** [comment] 2019-04-22 23:40
@stsewd I'm experiencing this too.

https://mdl-language.readthedocs.io/en/latest/ - Public. No problems.

https://mdl-language.readthedocs.io/en/sphinx/ - Private. It has built successfully, but I can't view it even though I'm logged in as the only project maintainer.

**Comment by daianagan** [comment] 2019-07-12 23:46
@taradinoc or anyone was able to solve this? I am still gettig the same error...

**Comment by dojutsu-user** [comment] 2019-07-13 05:04
@stsewd Seems like this is still valid. I am reopening the issue.

**Comment by taradinoc** [comment] 2019-07-13 07:56
@stsewd This is still reproducible using the links in my last comment. https://mdl-language.readthedocs.io/en/sphinx/ gives me a "Permission Denied" error even though I'm logged in as the admin.

**Comment by kmaehashi** [comment] 2019-07-18 09:17
Same case here. https://docs.chainer.org/en/v6/ (v6 branch is set to Private) cannot be browsed even when I logged in as a maintainer account.

**Comment by stsewd** [comment] 2019-07-18 19:40
Hi all, we are planning to remove the privacy levels from the community site, since all projects hosted in readthedocs.org are public open source projects. If you are relying on this feature to host private versions, you should use readthedocs.com instead.

With that said, I don't think this bug isn't going to be fixed soon (the core team is going to put more effort into removing the privacy levels)

Ref https://github.com/readthedocs/readthedocs.org/issues/2663 https://github.com/readthedocs/readthedocs.org/issues/3781

If you are using private versions with public open source projects, we would love to hear your use cases.

**Comment by daianagan** [comment] 2019-07-18 20:19
Dear @stsewd, 
Thanks for your reply. I didn't know that readthedocs.org was exclusively for open source projects, I thought readthedocs is an OS project itself but not that it was made for OS only also.
In my case I work as a Bioinformatician in a public hospital in Argentina and regularly I document patient's info which of course cannot be public. Another example are hospital's SOPs which cannot be made available for everyone. I found readthedocs & sphinx to be a very friendly way to show the documentation, but it won't be possible in my case if it has to be either public or paid (and regretfully I have no resources to pay for documentation). Or do you plan to have an option for non-profitable organizations? :)
I think I'll use Sphinx and local files for now
Thank you for your help!! 
Best regards, 
Daiana

**Comment by stsewd** [comment] 2019-07-18 20:47
@daianagan we do offer a discount for non-profitable organizations, and if that isn't enough or you have more questions, please write us to support@readthedocs.com

**Comment by kmaehashi** [comment] 2019-07-19 08:32
@stsewd Thank you for your reply! Let me explain our use-case.

We are currently developing in 2 branches; docs of `master` / `v6` branches are built as `latest` / `v6` version on RTD respectively. Our open-source project requires a bit complicated setup (building Python C++ extension modules that use CUDA), so we'd like to make sure that every commit of `master` / `v6` branches can be built successfully on RTD to avoid tagging a commit which cannot render docs correctly. Actually we once experienced that issue; of course, we're testing every commit by running `sphinx-build` on our own CI, but it is difficult to correctly reproduce the RTD build container environment.

To avoid confusion to users (because `v6` sounds like a docs of the latest released version of v6.x series, but actually it is a docs of HEAD of `v6` branch), we had been using `Protected` settings to `v6` branch, but unfortunately it was removed in #5833, so we considered migrating to `Private`, and found this issue.

I also think it's useful to have a Private mode as a "staging" feature so that we can try changing configuration in `readthedocs.yml` and see how it works in a separate branch. (So, actually what we need is the environment that can reproduce RTD results locally, not privacy levels.)

I understand that readthedocs.org is for public open source projects and thank you for providing a great service!

**Comment by stsewd** [comment] 2019-07-19 23:17
@kmaehashi would having build docs from a PR to preview the changes help with your use case? https://github.com/readthedocs/readthedocs.org/issues/1340

Also, we are going to have a replacement for `protected`, something like `hide` version, so those wouldn't be listed.

**Comment by kmaehashi** [comment] 2019-07-26 04:25
@steswd
> would having build docs from a PR to preview the changes help with your use case? #1340

Yes, that feature would be very useful for us.

> Also, we are going to have a replacement for protected, something like hide version, so those wouldn't be listed.

Thank you, looking forward to see that feature!

**Comment by saadmk11** [comment] 2019-09-12 06:01
Hi, @kmaehashi. We have The PR Builder Feature in BETA now. You can learn more about it in this blog post: https://blog.readthedocs.com/building-docs-for-pull-requests/

**Comment by kmaehashi** [comment] 2019-09-12 06:20
@saadmk11 Thanks for letting me know! I'll look into it.

**Comment by bsipocz** [comment] 2019-10-08 02:06
> Also, we are going to have a replacement for protected, something like hide version, so those wouldn't be listed.

do you have an ETA for this? We routinely used the "Protected" feature to hide our older versions, while keeping the direct lint to it alive. IMO the confusion could have been cleaned up with documentation rather than punishing with removal for those who it as intended.

**Comment by stsewd** [comment] 2019-10-08 03:02
We don't have a specific date, but it's on our roadmap https://github.com/readthedocs/readthedocs.org/pull/6194

**Comment by Borda** [comment] 2019-11-15 14:25
the same problem also for https://torch-lightning.readthedocs.io/en/docs 
from https://github.com/williamFalcon/pytorch-lightning/issues/465#issuecomment-554368986

**Comment by humitos** [comment] 2019-11-18 12:35
I think we can close this issue. We are not going to support PRIVATE versions on readthedocs.org --although, they will be fully supported on readthedocs.com

**Closed by humitos** 2019-11-18 12:35 UTC
Labels: Bug, Status: blocked

**Comment by Borda** [comment] 2019-11-18 12:52
So pls disable such option.

**Comment by humitos** [comment] 2019-11-18 13:07
@Borda we are working on that. Thanks,

**Comment by zilinc** [comment] 2019-12-21 12:12
I'm new to rtd. My use case is that I use private versions for debugging my docs (or as a preview as I fix things). Is there an alternative to it? Thanks in advance.

**Comment by humitos** [comment] 2019-12-22 12:22
@zilinc Hi! As mentioned in this issue, we are removing the support for private versions. In case you want to have "preview" of what a version will look like, you can ask to enable PR builder in your project. See https://blog.readthedocs.com/building-docs-for-pull-requests/
