### ISSUE TITLE
Build failed due to excessive memory consumption... even though mamba specified in config

### ISSUE THREAD

**Issue by maawoo** [readthedocs/readthedocs.org#9246] opened 2022-05-19 08:56 UTC
## Details

* Read the Docs project URL: https://readthedocs.org/projects/s1-nrb/
* Build URL (if applicable): https://readthedocs.org/projects/s1-nrb/builds/16953466/
* Project branch: https://github.com/SAR-ARD/S1_NRB/tree/docs 

## Expected Result

I expected my build to run successfully and without being killed due to excessive memory consumption by specifying the usage of Mambaforge in the `.readthedocs.yaml` config file. 

## Actual Result

The build I'm trying to test fails during the creation of the conda environment: 
```
>>conda env create --quiet --name docs --file environment-dev.yml
Collecting package metadata: ...working... done
Solving environment: ...working... Killed
Command killed due to timeout or excessive memory consumption
```

The only difference between the `environment-dev.yml`in this build and the last successful build on another branch, was the addition of the `nbsphinx` package.

I was happy to find out that mamba is supported after reading [this section](https://docs.readthedocs.io/en/stable/guides/conda.html#making-builds-faster-with-mamba) of the documentation and added a `.readthedocs.yaml` with the necessary settings. 

From the output of my failed build, I can't really tell if my `.readthedocs.yaml` is actually used or not. In my opinion this could be improved or am I missing something? And if it is actually used during build, I'm wondering why mamba is not used to create the environment.

**Comment by humitos** [comment] 2022-05-19 10:25
It seems that you have two Read the Docs config files and the one that's being used is the incorrect one, https://github.com/SAR-ARD/S1_NRB/blob/docs/readthedocs.yml. You should delete that file and the problem will be solved, I guess. Let me know.

**Comment by maawoo** [comment] 2022-05-19 10:44
That was the problem. Thanks for the quick reply!

I thought that this variant was deprecated and didn't think about it still interfering with the build process. Shouldn't a `.readthedocs.yaml` be prioritized if one is available?

**Comment by humitos** [comment] 2022-05-19 12:27
We should fail the build if we find multiple config files, because otherwise, it's confusing. I think we have an issue tracking that already. I'm closing this because the problem is solved.

**Closed by humitos** 2022-05-19 12:27 UTC
Labels: Support, Needed: more information
