### ISSUE TITLE
broken links in search results

### ISSUE THREAD

**Issue by godfryd** [readthedocs/readthedocs.org#6201] opened 2019-09-23 12:06 UTC
## Details

* Read the Docs project URL: https://readthedocs.org/projects/kea
* Docs site: https://kea.readthedocs.io/

When I do search for e.g. "configuration backend" I get broken links.
They are broken only on latest version. On v1_6_0 and when I'm building
and running Sphinx under my desk all is ok. I see that search engine
is different in RTD than in vanilla Sphinx.

## Expected Result

When I do search in latest version I get broken links:
https://kea.readthedocs.io/en/latest/search.html?q=configuration+backend&check_keywords=yes&area=default

## Actual Result

When I do search in v1_6_0 version I get ok links:
https://kea.readthedocs.io/en/v1_6_0/search.html?q=configuration+backend&check_keywords=yes&area=default#

**Comment by stsewd** [comment] 2019-09-23 15:33
Duplicate of https://github.com/readthedocs/readthedocs.org/issues/6069

**Closed by stsewd** 2019-09-23 15:33 UTC
