### ISSUE TITLE
Builds failing since pip update to 22.0 and 22.0.1

### ISSUE THREAD

**Issue by elParaguayo** [readthedocs/readthedocs.org#8864] opened 2022-01-30 22:06 UTC
## Description

Hi there,

I'm one of the maintainers for Qtile (https://www.github.com/qtile/qtile).

I've noticed that our docs (hosted by ReadTheDocs) have begun failing to build.

The error message is:
```
ERROR: Exception:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/qtile/envs/3274/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 165, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/docs/checkouts/readthedocs.org/user_builds/qtile/envs/3274/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/home/docs/checkouts/readthedocs.org/user_builds/qtile/envs/3274/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 389, in run
    to_install = resolver.get_installation_order(requirement_set)
  File "/home/docs/checkouts/readthedocs.org/user_builds/qtile/envs/3274/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 190, in get_installation_order
    expected_node_count=len(self._result.mapping) + 1,
  File "/home/docs/checkouts/readthedocs.org/user_builds/qtile/envs/3274/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 276, in get_topological_weights
    assert len(weights) == expected_node_count
AssertionError
````

The first failure (https://readthedocs.org/projects/qtile/builds/15928125/) was the first build following the release of 22.0.

The most recent failure (https://readthedocs.org/projects/qtile/builds/15931046/) also fails on 22.0.1.

## Expected behavior
Documents should build successfully.

I'm not aware of any other changes that would have impacted the building of our docs.

Would appreciate any support here.

I believe this is a `pip` issue, so I've posted an issue on their page too: https://github.com/pypa/pip/issues/10851

**Comment by boxed** [comment] 2022-01-31 00:29
I also have this problem.

I've been searching a long while now for a way to set pip version to the version before it broke, but I can't seem how to do that. It seems like there are two problem here:

1. pip broke
2. rtd projects can't work around it with a specific version of pip

**Comment by prisae** [comment] 2022-01-31 07:46
+1  -  I am having the same issue.

**Comment by yurabysaha** [comment] 2022-01-31 08:14
+1 - Same issue for 22.0.2

**Comment by naturalett** [comment] 2022-01-31 08:16
It solved me the issue:

`pip install -r requirements.txt --use-deprecated=html5lib --use-deprecated=legacy-resolver`

**Comment by humitos** [comment] 2022-01-31 08:43
Thanks for reporting this issue. I read https://github.com/pypa/pip/issues/10851 and it seems that it's a problem related to pip itself. I'm not sure yet if there is something that Read the Docs can do as a workaround to avoid this problem now. However, we will be taking a look at this and following that issue to understand the problem better and see if there is something we can do from our side.

I followed the steps from this comment and I was able to reproduce it https://github.com/pypa/pip/issues/10851#issuecomment-1025247713

However, downgrading pip to 21.3.1 (`pip install -U pip==21.3.1`) I was able to install the dependencies without issues. So, maybe Read the Docs could pin pip to that version.

**Comment by humitos** [comment] 2022-01-31 08:58
By pining pip in my local RTD instance, I was able to build https://github.com/qtile/qtile/commit/99e39b2fb973e22ffcbae5680ecf415851d6c531 properly. So, that could be a temporal solution we can implement.

**Comment by humitos** [comment] 2022-01-31 09:27
@elParaguayo @yurabysaha @prisae @boxed @naturalett Hi! I just deployed a quick hotfix that pins `pip==21.3.1` as a workaround for now. Can you confirm me that your documentation is building successfully now?

I triggered a build for qtile at https://readthedocs.org/projects/qtile/builds/15935061/ for the `latest` version and I _did passed_. So, I assume the rest of the projects should build properly as well.

**Comment by prisae** [comment] 2022-01-31 09:27
Tested it already, works perfectly now, thanks!

**Comment by boxed** [comment] 2022-01-31 09:29
Yep. Works now. Thanks for the super fast turn around!

**Comment by humitos** [comment] 2022-02-01 11:49
I'm closing this issue for now since the problem is workarounded in Read the Docs and there is no more work required from our side. We will remove the pin once `pip` releases a new version without this... bug? Thanks you all for reporting and all the work you are doing to solve this issue.

**Closed by humitos** 2022-02-01 11:49 UTC
