### ISSUE TITLE
Build time out when hitting the api to get active versions

### ISSUE THREAD

**Issue by ChoiByungWook** [readthedocs/readthedocs.org#6304] opened 2019-10-17 18:42 UTC
## Details:

* Project URL: https://readthedocs.org/projects/sagemaker/
* Build URL(if applicable): https://readthedocs.org/projects/sagemaker/builds/9817944/
* Read the Docs username(if applicable): AnonymousUser

## Expected Result

Build succeed

## Actual Result

Based on the build history, the builds have been failing and passing inconsistently.

The following things are inconsistent when looking at our build history:

1. Build time (succeeds and failures ranging from 70s - 220s)
2. Build log output (log outputs for failed builds are inconsistent)
3. Error indication (A lot of the failed builds don't display any obvious error, as listed below.)

Can we get some insight into why the builds failed, specifically for these:

* https://readthedocs.org/api/v2/build/9813741.txt
* https://readthedocs.org/api/v2/build/9813710.txt
* https://readthedocs.org/api/v2/build/9813681.txt
* https://readthedocs.org/api/v2/build/9813550.txt
* https://readthedocs.org/api/v2/build/9813542.txt
* https://readthedocs.org/api/v2/build/9813533.txt
* https://readthedocs.org/api/v2/build/9807045.txt

The peculiar thing is that this next build succeeded but it was a one line change in the code, with not much changes in the RST or documentation.

* https://readthedocs.org/projects/sagemaker/builds/9817945/

Corresponding changes for the build above:

* https://github.com/aws/sagemaker-python-sdk/commit/9c07f0611eafb8ca33f1d86836468e52e3ce04dc
* https://github.com/aws/sagemaker-python-sdk/pull/1087/files

**Comment by laurenyu** [comment] 2019-10-24 21:00
any update? we're continuing to see a lot of transient failures, especially when multiple builds in the same project are run simultaneously

**Comment by stsewd** [comment] 2019-10-25 02:53
It may be related to time outs, I'll increase the build time of the projects on monday

**Comment by laurenyu** [comment] 2019-10-28 22:10
thanks for your help!

**Comment by laurenyu** [comment] 2019-10-29 17:53
@stsewd were you able to increase the build time yesterday? the failures have become more consistent now, but the error message simply says "There was a problem with Read the Docs while building your documentation. Please try again later. However, if this problem persists, please report this to us with your build id"

**Comment by stsewd** [comment] 2019-10-29 22:33
Sorry, I wasn't able to get to this yesterday, I'm checking now.

**Comment by stsewd** [comment] 2019-10-29 23:27
Looking at this doesn't look like it's from timeout. Not sure what's causing it. I'm investigating a little more

**Comment by stsewd** [comment] 2019-10-30 00:07
I wasn't able to reproduce this locally, but I found this in the logs 

```
readthedocs.doc_builder.environments:619[24217]: ERROR (Build) [sagemaker:stable] HTTPSConnectionPool(host='10.32.16.11', port=10443): Max retries exceeded with url: /api/v2/project/164476/active_versions/ (Caused by ResponseError('too many 502 error responses',))
```

**Comment by laurenyu** [comment] 2019-10-30 16:44
hmm was there anything around that line that might suggest what could be causing the 502 response?

**Comment by stsewd** [comment] 2019-10-30 16:48
I'm investigating that. It's probably a slow query.

**Comment by stsewd** [comment] 2019-10-30 18:56
Looks like the slowness is because the amount of active versions your project has (149). I'm seeing the same on projects that have more than 100 active versions. This number of project with more than 100 active versions is really low, though. There are only 7 projects affected by this.

The explanation, we are hitting azure cloud storage to check if the epub, zip, pdf files exists https://github.com/readthedocs/readthedocs.org/blob/d298ff5d6d71adfcd424051894710a38d10b550f/readthedocs/projects/models.py#L779-L791
The API returns that here https://github.com/readthedocs/readthedocs.org/blob/d298ff5d6d71adfcd424051894710a38d10b550f/readthedocs/api/v2/serializers.py#L79-L79

(but we actually don't use that value for building)

Anyway, we are in the progress of a solution to avoid querying azure that much https://github.com/readthedocs/readthedocs.org/pull/6278

In the mean time, if you don't really need to keep all 149 versions active, you can disable them https://readthedocs.org/projects/sagemaker/versions/. Having less than 100 active versions should make the builds happy again.

**Comment by laurenyu** [comment] 2019-10-30 21:38
Great, thanks for digging into this! I see #6278 has been merged - is there an ETA on when that will be released?

**Comment by stsewd** [comment] 2019-10-30 21:40
@laurenyu the above PR is just one part of what needs to be done to reduce the number of queries.

**Comment by stsewd** [comment] 2019-12-04 02:19
We now don't query azure anymore https://github.com/readthedocs/readthedocs.org/blob/ae6aeb5837324b32e57623913f57fa9d9b216169/readthedocs/builds/models.py#L375-L399

**Closed by stsewd** 2019-12-04 02:19 UTC
Labels: Bug, Status: blocked
