### ISSUE TITLE
matplotlib.ft2font.FT2Font error instead of plot in .ipynb document

### ISSUE THREAD

**Issue by steko** [readthedocs/readthedocs.org#9552] opened 2022-08-26 09:57 UTC
## Details

* Read the Docs project URL: https://readthedocs.org/projects/iosacal/
* Build URL (if applicable): https://readthedocs.org/projects/iosacal/builds/17903036/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/steko/

## Expected Result

The iosacal docs are based on MyST-NB.

The Jupypter notebook cell in `docs/index.ipynb` should return a plot, as was correctly shown in previous versions e.g. https://iosacal--26.org.readthedocs.build/en/26/ and in other pages of the documentation in the current build.

## Actual Result

Instead of the plot, the following message is shown:

```
Matplotlib is building the font cache; this may take a moment.

Exception ignored in: <matplotlib.ft2font.FT2Font object at 0x7fbe6a275420>
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/iosacal/envs/latest/lib/python3.10/site-packages/matplotlib/font_manager.py", line 1092, in addfont
    font = ft2font.FT2Font(path)
KeyboardInterrupt: 

```

**Comment by steko** [comment] 2022-08-28 10:32
Changing os to 20.04 doesn't solve the issue https://readthedocs.org/projects/iosacal/builds/17917241/

**Comment by humitos** [comment] 2022-08-29 08:14
Hi @steko. I don't think this is an issue related to Read the Docs. I'd think it's related to some dependency being upgraded, for example. I'd recommend you to read this document https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html and pin your dependencies to the ones that were working before.

**Comment by steko** [comment] 2022-08-29 12:48
Hi @humitos thank you for your suggestion. Locally, I can compile the entire documentation just fine on Python 3.10, with both Windows and Linux, using the most recent versions of our dependencies and in particular Sphinx 5.1.1.

These are the results on Read the Docs:

| os | python | sphinx | result |
| -------- | -------- | -------- |--------|
| 22.04     | 3.10     | 5.1.1     | ❌ |
| 20.04     | 3.10     | 5.1.1     | ❌ |
| 20.04     | 3.10     | 4.5.0     | ❌ |
| 20.04     | 3.8     | 4.5.0     | ✔️ |
| 20.04     | 3.8     | 5.1.1    | ❌ |
| 20.04     | 3.9     | 5.1.1    | ✔️ |

Apparently something is misbehaving on Python 3.10. I will downgrade to Python 3.9, since that works well for my use case. I leave it to you whether this issue can be closed or left open.

**Comment by humitos** [comment] 2022-08-29 14:39
BTW, it's pretty weird that the exception reported in the build process `KeyboardInterrupt`.

@steko can you tell me a particular branch on your project that is currently having this problem? That way, we will be able to do some tests on a local Read the Docs instance and trace the issue.

**Comment by steko** [comment] 2022-08-29 14:56
> BTW, it's pretty weird that the exception reported in the build process `KeyboardInterrupt`.

I know! And it only happens with some combinations of Python and Sphinx version. 

> @steko can you tell me a particular branch on your project that is currently having this problem? That way, we will be able to do some tests on a local Read the Docs instance and trace the issue.

I think you could try with this commit https://codeberg.org/steko/iosacal/commit/3f67d05b3bf78268ab6a1bc28a57997ce67c4cfd (it's on the main branch, but there are newer commits that work around the issue).

**Comment by dibble07** [comment] 2023-02-15 19:19
I had the exact same issue. Fixing my Matplotlib version to 3.6.0 from 3.7.0 seemed to resolve it. See 4b2a06e04918360241b024bc62c2ecb10073ebab if you want to try reproduce.

**Comment by humitos** [comment] 2023-02-16 07:56
@dibble07 thanks for sharing! I'll close the issue then since it seems to be an issue with an old version of Matplotlib and not on Read the Docs.

**Closed by humitos** 2023-02-16 07:56 UTC
Labels: Support, Needed: replication

**Comment by dibble07** [comment] 2023-02-16 08:00
@humitos I don't think it's exclusively to blame on Matplotlib. The setup I had using 3.7.0 worked perfectly fine locally so it seems to be something to do with the combination of Matplotlib and the RTD container.
