### ISSUE TITLE
ModuleNotFoundError: No module named 'setuptools._distutils'

### ISSUE THREAD

**Issue by knc6** [readthedocs/readthedocs.org#8775] opened 2021-12-20 15:25 UTC
Hi,

We use readthedocs for the [jarvis-tools](https://jarvis-tools.readthedocs.io/) package. Recently, I am seeing an error due to setuptools:

Raw log here: https://readthedocs.org/api/v2/build/15584283.txt

I am wondering if somebody can help me with this.

---

📌 _Edit by @astrojuanlu_ 📌 This issue is triggered by [setuptools 60](https://setuptools.pypa.io/en/latest/history.html#v60-0-0), released on 2021-12-19. Current status:

- ~If your project _doesn't_ have a `pyproject.toml`, most likely you have the "use system packages" version enabled. You can (1) disable it, (2) cap setuptools yourself in your requirements, or (3) wait for us to deploy a fix (January 2022) . See [below](https://github.com/readthedocs/readthedocs.org/issues/8775#issuecomment-998366541) for more context.~ **Update: This has been fixed on RTD as of Dec 21.**
- If your project _does_ have a `pyproject.toml`, most likely pip is using its fallback mode and installing the problematic setuptools version in an isolated environment. In this case, there is nothing Read the Docs can do to fix your problem. You can do it yourself by adding a proper `[build-system]` PEP 518 table to your `pyproject.toml` file. See [below](https://github.com/readthedocs/readthedocs.org/issues/8775#issuecomment-998878270) for more information.
- You can temporarily roll back to the old setuptools behavior by exporting a `SETUPTOOLS_USE_DISTUTILS=stdlib` environment variable for your project. However, it is not guaranteed that this will work forever, and we encourage you to look into the solution above.
- If you were redirected here, it's because you opened a new issue for this exact problem. Please try the solution above first.
- If it didn't work, leave a comment below with a link to your failing build.

**Comment by bhazelton** [comment] 2021-12-20 18:04
We're seeing the same problem on PR builds for the [pyuvdata](https://pyuvdata.readthedocs.io/en/latest/index.html) package. 

This is the log:
https://readthedocs.org/projects/pyuvdata/builds/15585777/

I've done some digging, I think this is caused by setuptools version 60.0 first being installed and then downgraded to version 58.2.0. See these related issues:
https://github.com/pypa/setuptools/issues/2939
https://github.com/pypa/setuptools/issues/2353

It seems that this first came up when version 50.0 was released. They fixed it up but then changed it again in 60.0 (with documentation in the changelog). From reading about the issue in 50.0, it seems like this interacts with a bug in pip where the paths get confused when you have one version installed then removed and a different version installed (https://github.com/pypa/setuptools/issues/2353#issuecomment-685217078).

**Comment by knc6** [comment] 2021-12-20 19:45
Interesting, that seems very likely.

I temporarily fixed the issue by getting rid of one of the optional dependencies (phonopy) which was creating the problem.

**Comment by astrojuanlu** [comment] 2021-12-20 20:31
Thanks @knc6 for the report and @bhazelton for the help. I have found in your build logs that the line `/home/docs/checkouts/readthedocs.org/user_builds/jarvis-tools/envs/develop/bin/python -m pip install --upgrade --no-cache-dir -I mock==1.0.1 pillow==5.4.1 alabaster>=0.7,<0.8,!=0.7.5 commonmark==0.8.1 recommonmark==0.5.0 sphinx<2 sphinx-rtd-theme<0.5 readthedocs-sphinx-ext<2.2` brings setuptools 60.0.0 again, even after doing `/home/docs/checkouts/readthedocs.org/user_builds/jarvis-tools/envs/develop/bin/python -m pip install --upgrade --no-cache-dir pip setuptools<58.3.0` right before. I don't think this is a problem with RTD but I want to try and reproduce this, so I'm reopening.

**Comment by astrojuanlu** [comment] 2021-12-20 20:32
Oh, of course I understand why. We're passing `--upgrade` in the second `pip install` command, so the `pip install setuptools<58.3.0` is useless. This will need a fix.

**Comment by zaneselvans** [comment] 2021-12-20 23:36
We also seem to be experiencing this problem:

https://readthedocs.org/projects/catalystcoop-pudl/builds/15588383/

**Comment by astrojuanlu** [comment] 2021-12-21 00:21
I see that both catalystcoop-pudl from @zaneselvans and jarvis-tools from @knc6 have the "use system packages" option enabled. For this reason, the second `pip install` command adds a `-I, --ignore-installed` and that's why the newer setuptools gets installed:

https://github.com/readthedocs/readthedocs.org/blob/c3b4bef6bde1b0717da19d5504749edaa68c7045/readthedocs/doc_builder/python_environments.py#L523-L528

I anticipated setuptools breakage in #8711 (and probably it's thanks to it that we aren't seen dozens of user reports) but I didn't realize that the `-I` flag was being added in some cases.

I'm about to push a fix that hopefully will get deployed soon, but in the meantime, can you test if disabling the "use system packages" option does the trick? And, if you are using it because of some other reason, state why?

**Comment by bhazelton** [comment] 2021-12-21 00:45
I checked and we had the "use system packages" option enabled as well, I don't recall why. I unchecked it and re-ran the builds and they passed. So that fixed it for us. Thank you!

**Comment by zaneselvans** [comment] 2021-12-21 00:50
We were using the system packages because we depend on Matplotlib, scipy, numpy, etc. and wanted to avoid installing them from scratch. But turning off system packages seems to have fixed the issue.

**Comment by uvchik** [comment] 2021-12-21 15:23
We have the same issue but I cannot see that we added explicitly "use system packages". I also tried `setuptools<58.3.0` and it worked. During the process setuptool is downgraded to `58.2.0` but this does not solve the problem. Any hints?

Project: [oemof/oemof-solph](https://github.com/oemof/oemof-solph)
RTD-log: https://readthedocs.org/projects/oemof-solph/builds/15593968/

**Comment by astrojuanlu** [comment] 2021-12-21 15:34
@uvchik I think your case is slightly different. [Since your project has a `pyproject.toml` file, pip triggers a different install mode that performs build isolation](https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/?highlight=pyproject.toml#build-isolation):

> For building packages using this interface, pip uses an isolated environment. That is, pip will install build-time Python dependencies in a temporary directory which will be added to sys.path for the build commands.

Then, [since your `pyproject.toml` does not define build-time dependencies as per PEP 518, pip uses a fallback mode](https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/?highlight=pyproject.toml#fallback-behaviour). Therefore, no matter what setuptools version you install in your `requirements.txt`, and _no matter what version we magically install for you_, pip will use the newest version that fits the `"setuptools>=40.8.0"` pinning. In your case, the problematic setuptools 60.x.

The solution in your case is to add the following contents to your `pyproject.toml`:

```
[build-system]
requires = ["setuptools<60.0", "wheel"]
build-backend = "setuptools.build_meta"
```

Can you please try it and let us know if it works?

**Comment by astrojuanlu** [comment] 2021-12-21 15:49
Added detailed instructions with several methods to fix this issue in the first comment ☝🏽

**Comment by uvchik** [comment] 2021-12-21 15:55
Thank you. Works fine.

**Comment by astrojuanlu** [comment] 2021-12-22 12:44
Leaving this issue pinned so folks can easily find it, but we have done our part from the RTD side already to avoid that most projects experience it, so I am closing it. Feel free to continue the conversation here, but remember to [read the current status in the first comment](https://github.com/readthedocs/readthedocs.org/issues/8775#issue-1084917371) before doing so.

**Closed by astrojuanlu** 2021-12-22 12:44 UTC

**Comment by BootsManOut** [comment] 2022-10-13 22:29
Hello,

I do not have a _**pyproject.toml**_ file anywhere.
How can I fix this issue?

**Comment by kambyzkargrshhamt** [comment] 2022-10-14 04:49
Hello, my dears, I am not feeling well, my mobile phone is not working properly, Google Play, Google Chrome engine is blacked out, my daughter is not in the mood, what can I say.

**Comment by kambyzkargrshhamt** [comment] 2022-10-14 04:51
In the forum, you can write a program to convert a mobile phone or a satellite receiver into a transmitter-receiver, so that data can be downloaded from the Internet.

**Comment by kambyzkargrshhamt** [comment] 2022-10-14 04:53
I went to get medicine, I got shot in my foot, I was bleeding for 3 days, one of my friends took 25 bullets out of my foot, I am a bit better, but I can't walk, my daughter wants medicine, death came to my husband.

**Comment by kambyzkargrshhamt** [comment] 2022-10-14 04:57
open an account for me with a number, transfer me, what should I do, an Irish girl gave my daughter 3 gifts, she won't pay with the exchange payment code, she is eating, what should I do, who should I tell, Willow Kubin Ethereum 6.12.409.813b et

**Comment by kambyzkargrshhamt** [comment] 2022-10-14 04:58
A ten-year-old man gave me, see how it is being abused, why don't you give me what is my sin, my sin is to breathe

**Comment by kambyzkargrshhamt** [comment] 2022-10-14 05:01
Hello, I have a phone, I don't have a laptop, then you have to put the
program on your phone. my dears

۱۶۱۵

در تاریخ جمعه ۱۴ اکتبر ۲۰۲۲،‏ ۱:۵۹ BootsManOut ***@***.***>
نوشت:

**Comment by kambyzkargrshhamt** [comment] 2022-10-14 05:02
Now it is very difficult to go to the program, it was very difficult

۱۶۱۵

در تاریخ جمعه ۱۴ اکتبر ۲۰۲۲،‏ ۸:۳۱ کامبیز کارگر شهامت <
***@***.***> نوشت:

**Comment by kambyzkargrshhamt** [comment] 2022-10-14 05:04
I don't have a filter blocker, all Google Play apps, Google Chrome engine
don't work

۱۶۱۵

در تاریخ جمعه ۱۴ اکتبر ۲۰۲۲،‏ ۸:۳۲ کامبیز کارگر شهامت <
***@***.***> نوشت:

**Comment by kambyzkargrshhamt** [comment] 2022-10-14 05:06
Now for us, the Internet is allowed from the point of view of America,
there is no problem even to give a license

۱۶۱۵

در تاریخ جمعه ۱۴ اکتبر ۲۰۲۲،‏ ۸:۳۳ کامبیز کارگر شهامت <
***@***.***> نوشت:
