### ISSUE TITLE
[error occurred in build.] ImportError: cannot import name 'environmentfilter' from 'jinja2' 

### ISSUE THREAD

**Issue by lixiang007666** [readthedocs/readthedocs.org#9038] opened 2022-03-25 07:04 UTC
## Details

* Read the Docs project URL: https://readthedocs.org/projects/libai/
* Build URL (if applicable): https://readthedocs.org/projects/libai/builds/16464179/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/Lixiang666007/

## Expected Result

*Without any changes to the doc, the following error suddenly appeared!*

<img width="873" alt="image" src="https://user-images.githubusercontent.com/54010254/160070685-49a43eea-ec41-4264-9da2-f66b17557c49.png">

```
/home/docs/checkouts/readthedocs.org/user_builds/libai/envs/latest/bin/python -m sphinx -T -E -b html -d _build/doctrees -D language=en . _build/html
Traceback (most recent call last):
  File "/home/docs/.asdf/installs/python/3.7.12/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/docs/.asdf/installs/python/3.7.12/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/libai/envs/latest/lib/python3.7/site-packages/sphinx/__main__.py", line 13, in <module>
    from sphinx.cmd.build import main
  File "/home/docs/checkouts/readthedocs.org/user_builds/libai/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 25, in <module>
    from sphinx.application import Sphinx
  File "/home/docs/checkouts/readthedocs.org/user_builds/libai/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 43, in <module>
    from sphinx.registry import SphinxComponentRegistry
  File "/home/docs/checkouts/readthedocs.org/user_builds/libai/envs/latest/lib/python3.7/site-packages/sphinx/registry.py", line 24, in <module>
    from sphinx.builders import Builder
  File "/home/docs/checkouts/readthedocs.org/user_builds/libai/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 26, in <module>
    from sphinx.util import import_object, logging, progress_message, rst, status_iterator
  File "/home/docs/checkouts/readthedocs.org/user_builds/libai/envs/latest/lib/python3.7/site-packages/sphinx/util/rst.py", line 21, in <module>
    from jinja2 import Environment, environmentfilter
ImportError: cannot import name 'environmentfilter' from 'jinja2' (/home/docs/checkouts/rea
```

## Actual Result

**The previous builds were normal, I didn't make any changes.**

**Comment by lixiang007666** [comment] 2022-03-25 10:14
🫃🏿

**Comment by Brawcks** [comment] 2022-03-25 11:07
Same here 👍

**Comment by ChuanXu1** [comment] 2022-03-25 11:26
This may be due to the latest release of Jinja2. Requiring Jinja2<3.1 fixes my issue.

**Comment by lixiang007666** [comment] 2022-03-25 11:38
> This may be due to the latest release of Jinja2. Requiring Jinja2<3.1 fixes my issue.

What does `Jinja2<3.1` refer to? How did you fix it?👀

**Comment by lixiang007666** [comment] 2022-03-25 12:00
https://github.com/sphinx-doc/sphinx/issues/10291

**Comment by ChuanXu1** [comment] 2022-03-25 12:04
> > This may be due to the latest release of Jinja2. Requiring Jinja2<3.1 fixes my issue.
> 
> I didn't import `Jinja` module manually, How did you fix it?👀

you can explicitly add `Jinja2<3.1` in the configuration

**Comment by ericholscher** [comment] 2022-03-25 14:58
This is a dupe of the comment yesterday. The best approach is to fully pin your dependencies as noted here: 

https://github.com/readthedocs/readthedocs.org/issues/9037#issuecomment-1077818554

**Comment by humitos** [comment] 2022-03-28 10:34
We deploy a hotfix for this. We still recommend you to pin your dependencies, tho 😄

**Closed by humitos** 2022-03-28 10:34 UTC

**Comment by gordon07815** [comment] 2023-10-03 11:00
> This may be due to the latest release of Jinja2. Requiring Jinja2<3.1 fixes my issue.

This works for me.
Thanks a lot!!
