### ISSUE TITLE
Caption of index.rst works wrong

### ISSUE THREAD

**Issue by chaoming0625** [readthedocs/readthedocs.org#8069] opened 2021-04-05 03:30 UTC
## Details

* Read the Docs project URL: https://brainmodels.readthedocs.io/
* Build URL (if applicable): https://readthedocs.org/api/v2/build/13424705.txt
* Read the Docs username (if applicable): 

## Expected Result

The "caption" in index.rst should be highlighted and should be made as the title. Also, it shold be capitalized in the navigation bar. 

## Actual Result

However, the index.rst "caption" works very differently. It is not rendered the title in the main page and not rendered  as usual capitalized words in the navigation bar.

**Comment by Blendify** [comment] 2021-04-05 03:55
Please see https://github.com/readthedocs/sphinx_rtd_theme/issues/1112 for a temporary fix

**Comment by Blendify** [comment] 2021-04-05 05:50
Closing as a duplicate of https://github.com/readthedocs/sphinx_rtd_theme/issues/1112. The bug will need to be fixed in the theme, not here.

**Closed by Blendify** 2021-04-05 05:50 UTC
Labels: Bug, Priority: high
