### ISSUE TITLE
auto export `.readthedocs.yml` from website settings

### ISSUE THREAD

**Issue by graingert** [readthedocs/readthedocs.org#7463] opened 2020-09-07 09:47 UTC
I'd like to have a button to generate a `.readthedocs.yml` from my control panel so I can paste it into github

Even better would be a button to make a PR to my project that contains the file

**Comment by graingert** [comment] 2020-09-07 09:48
currently the process is very manual https://docs.readthedocs.io/en/stable/config-file/v2.html#migrating-from-the-web-interface

**Comment by stsewd** [comment] 2020-09-08 15:51
Duplicate of https://github.com/readthedocs/readthedocs.org/issues/4746

**Closed by stsewd** 2020-09-08 15:51 UTC
Labels: Feature
