### ISSUE TITLE
Support multiple languages from single conf.py source

### ISSUE THREAD

**Issue by wqh17101** [readthedocs/readthedocs.org#4338] opened 2018-07-07 01:25 UTC
These will be very useful when you want to generate multi-language documents. You will never must create many rtd projects only for translation.
Example:
you can design that these documents are `startswith('docs')`  such as (docs_zh,docs_en,docs_ja)and have conf.py and something necessary of the docs now. The language will be set in the conf.py. 
Then you can clone,copy,generate one by one.

**Comment by stsewd** [comment] 2018-07-07 12:29
I'm just linking to the related discussion https://github.com/rtfd/readthedocs.org/issues/4315#issuecomment-402066050

**Comment by agjohnson** [comment] 2018-08-03 00:41
We already support this manually. You need to specify the conf.py path in the translation project admin.

Eventually, I think this feature is not to guess the project translation path. We would instead just use a single conf.py and override the language parameters in the conf.py.

**Comment by humitos** [comment] 2019-01-07 17:43
> Eventually, I think this feature is not to guess the project translation path. We would instead just use a single conf.py and override the language parameters in the conf.py.

Aren't we already doing this by using `-D language={lang}`?

https://github.com/rtfd/readthedocs.org/blob/d91807c5c772fbfdb4be5ff928c9268d4be05e80/readthedocs/doc_builder/backends/sphinx.py#L220

If this is not what you refers to, I'm not sure to understand what is the actionable part of this issue.

**Comment by stsewd** [comment] 2019-01-08 00:56
@humitos the issue is about having to create a project for each translation when we could just create one and run the command `-D language={lang}` with several languages that the user requires.

**Comment by humitos** [comment] 2019-01-08 10:38
> @humitos the issue is about having to create a project for each translation when we could just create one and run the command `-D language={lang}` with several languages that the user requires.

We will need a way to

1. auto discover the translations, or
1. give an option to the user to specify what languages they want to build

Also, we will need to re-think how we manage project `main_language` and how project translation are linked each other to be able to produce the flyout menu (and other places) with all the languages.

I'm not seeing clear way to implement this at the moment.

**Comment by tlongers** [comment] 2019-09-26 12:52
Arrived here through https://github.com/readthedocs/readthedocs.org/issues/4315#issuecomment-402066050 after experiencing some difficulties in understanding how to configure RTD to handle multi-lingual documentation. 

RTD's documentation on the current way to internationalise is /almost/ there, but I'm with the OP that there are some missing connections between the steps required to localise (generating .po files, setting up locale/ etc) and those required to configure RTD to display the localisations.  The things I learned, and pending a feature update, that could be clearer in the docs are:

- Multiple projects in RTD can be created from the same GitHub repository hosting my Sphinx docs, which is done through the "Manual upload" option.
- if I use `sphinx-intl` to create multiple locales my Sphinx project, each locale corresponds to a project I must create in RTD .
- Choosing the language in "Admin -> Settings" in the RTD project for a locale means RTD goes fishing in `~/source/locale` for the relevant .po files for that language and will build it in that language. What I was also not clear on is how this step relates to specifying the `.conf` path manually for each project - what have I missed?
- Group all the locale-specific projects together using "Admin -> Translations" in the project you've decided is the parent. 
- Once set up I only then need to maintain a single repository, updating different locales as needed. With each updated pushed, RTD will rebuild all projects drawn from that repository.

I write all the above to  be constructive and help anyone else experiencing the issue. As ever am deeply grateful you have used your time and skills to create this great platform which we use for free!

**Comment by mmaridev** [comment] 2020-02-05 07:22
+1

**Comment by lfoppiano** [comment] 2021-05-16 23:20
>     * Choosing the language in "Admin -> Settings" in the RTD project for a locale means RTD goes fishing in `~/source/locale` for the relevant .po files for that language and will build it in that language. What I was also not clear on is how this step relates to specifying the `.conf` path manually for each project - what have I missed?


As a matter of fact, what is the answer to this question? 

I'm stuck at the same point here 🙏

**Comment by stsewd** [comment] 2021-05-17 14:41
> > Choosing the language in "Admin -> Settings" in the RTD project for a locale means RTD goes fishing in `~/source/locale` for the relevant .po files for that language and will build it in that language. What I was also not clear on is how this step relates to specifying the `.conf` path manually for each project - what have I missed?
> 
> As a matter of fact, what is the answer to this question?
> 
> I'm stuck at the same point here pray

Do you mean a conf.py file from sphinx? We use the selected language to invoke sphinx with that option under the directory you chose from the conf.py file.

**Comment by lfoppiano** [comment] 2021-05-17 23:20
Yes so the solution is to create a new project on readthedocs and select a different language, then set the newly created project as the translation of the main one (usually in english?). 

It's actually documented [here](https://docs.readthedocs.io/en/stable/localization.html#project-with-multiple-translations) but it was not clear the first time I read it.

**Comment by stsewd** [comment] 2021-05-19 15:08
> Yes so the solution is to create a new project on readthedocs and select a different language, then set the newly created project as the translation of the main one (usually in english?).
> 
> It's actually documented [here](https://docs.readthedocs.io/en/stable/localization.html#project-with-multiple-translations) but it was not clear the first time I read it.

yeah, please feel free to send a PR with the changes that would have made this more clear!

**Comment by humitos** [comment] 2023-09-06 12:41
I understand that OP wants create only one Read the Docs project and run Sphinx multiple times to generate multiple language output. Like, `_build/html/en/`, `_build/html/ja/`, etc.

With the introduction of `build.commands` config key (see https://docs.readthedocs.io/en/latest/config-file/v2.html#build-commands) this can be achieved as follows:

```yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  commands:
    - pip install -r docs/requirements.txt
    - sphinx-build -b html -D language=en docs/ $READTHEDOCS_OUTPUT/html/en/
    - sphinx-build -b html -D language=ja docs/ $READTHEDOCS_OUTPUT/html/ja/
```

This will be served at `<slug>.readthedocs.io/en/latest/en/` and `<slug>.readthedocs.io/en/latest/ja/` which, as you can see, it shows the `/en/` part twice in the English version and once in the Japanese one. However, we are working to allow removing that part of the URL in https://github.com/readthedocs/readthedocs.org/issues/10307 and it will be soon possible to do.

When #10307 is deployed, those URL would look like:

* `<slug>.readthedocs.io/latest/en/`
* `<slug>.readthedocs.io/latest/ja/`

Note this is not _the final_ solution, but more like a **workaround** to the original limitation.

> You will never must create many rtd projects only for translation.

**The recommended way to solve this problem is to create one Read the Docs project per translation** 👍🏼 .

**Comment by humitos** [comment] 2023-09-06 12:46
I'm going to close this issue since we don't plan to implement what OP suggests unfortunately. We _require_ having multiple Read the Docs projects (one per language) to support translations in the way we do. Feel free to re-open if you consider there is anything from our side that we can do, tho.

**Closed by humitos** 2023-09-06 12:46 UTC
Labels: Feature, Needed: design decision
