### ISSUE TITLE
ReadTheDocs search and MkDocs

### ISSUE THREAD

**Issue by d0ugal** [readthedocs/readthedocs.org#1088] opened 2014-12-13 16:05 UTC
(Sorry for adding this as an issue @ericholscher, but we keep missing each other on IRC. If there is a better place, let me know.)

We added the `mkdocs json` command to MkDocs for RTD's to use in serverside search. Since then I have been [working on clientside search](https://github.com/tomchristie/mkdocs/pull/222) support. This means we generate a JSON index in a slightly different format to work with Tipue search and thus we will potentially have two different JSON output formats which is a bit of a pain.

The Tipue format looks like this: https://github.com/Tipue/Tipue-Search/blob/master/tipuesearch/tipuesearch_content.js . The key difference is that it is one file containing all pages and the key names are different but otherwise I think it contains pretty much the same data.

So, my question is, can RTD be adapted to use this format so we can drop the specific json command from MkDocs? If so, I'd be happy to make the change in the ReadTheDocs code.

**Comment by marcelstoer** [comment] 2016-02-27 22:12
Is still relevant? `mkdocs json` has since become deprecated...

**Comment by d0ugal** [comment] 2016-02-27 23:18
Yes, I believe this is relevant. We have deprecated it in MkDocs but we won't remove it while RTD still depends on it.

**Comment by marcelstoer** [comment] 2016-02-27 23:23
Fair enough. Sorry, I was mislead but I'm grasping at straws trying to figure out why the search for *some* MkDocs projects works on RTD but not for others (#2020).

**Comment by d0ugal** [comment] 2016-02-28 10:20
No problem. I'm not sure how to help you with that issue, I'm not familiar with RTD's search.

**Comment by ergonlogic** [comment] 2016-05-24 20:54
It appears that the form action for the searchbox is being injected with this javascript: https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/core/static-src/core/js/doc-embed/mkdocs.js.

It looks like it's just building the wrong query, along the lines of: `https://readthedocs.org/search/?q=bar&check_keywords=yes&area=default&project=foo&version=X.y&type=file`. Either of these paths actually work though:

- https://readthedocs.org/projects/foo/search/?q=bar
- http://foo.readthedocs.io/en/X.y/search.html?q=bar

**Comment by marcelstoer** [comment] 2016-05-24 21:37
Thanks for the hint. The first doesn't work for me but the second does:

- https://readthedocs.org/projects/nodemcu/search/?q=docker -> NOK, no results
- http://nodemcu.readthedocs.io/en/dev/search.html?q=docker -> OK

**Comment by ergonlogic** [comment] 2016-05-24 22:17
The easiest work-around for this is overriding the searchbox template like so: https://github.com/aegir-project/documentation/compare/2884f80...3a44eec1

Note the change in the form's `id` (e.g. `rtd-search-form-alt`). This stops the RTD JS from breaking the default search functionality.

**Comment by marcelstoer** [comment] 2016-05-25 05:09
The fact that your work-around has the desired affect means that RTD by default replaces the MkDocs RTD theme? The original theme's `searchbox.html` isn't so different from yours: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/themes/readthedocs/searchbox.html. So, the custom theme kinda re-introduces the original theme?

**Comment by ergonlogic** [comment] 2016-05-25 12:16
RTD isn't replacing the mkdocs theme, just altering it with some javascript. As per http://www.mkdocs.org/user-guide/custom-themes/#creating-a-custom-theme, I just copied the default mkdocs RTD theme's searchbox.html, and altered the form id, so that the JS would no longer have any effect.

**Comment by marcelstoer** [comment] 2016-06-08 20:20
@ergonlogic the only "problem" with your nifty custom theme approach I found so far is that RTD changes the implementation of the footer fly-out menu it adds. While it normally sits in the lower left corner it is moved to the lower right and becomes detached once you declare a custom theme in `mkdocs.yml`.
An alternative is to add the following JavaScript function to your `extra.js`. It reverts the changes RTD applies to the search form:

```javascript
  function fixSearch() {
    var target = document.getElementById('rtd-search-form');
    var config = {attributes: true, childList: true};

    var observer = new MutationObserver(function(mutations) {
      // if it isn't disconnected it'll loop infinitely because the observed element is modified
      observer.disconnect();
      var form = $('#rtd-search-form');
      form.empty();
      form.attr('action', 'https://' + window.location.hostname + '/en/' + determineSelectedBranch() + '/search.html');
      $('<input>').attr({
        type: "text",
        name: "q",
        placeholder: "Search docs"
      }).appendTo(form);
    });
    // don't run this outside RTD hosting
    if (window.location.origin.indexOf('readthedocs') > -1) {
      observer.observe(target, config);
    }
  }
```

**Comment by sahilTakiar** [comment] 2016-07-03 18:59
Thanks you @marcelstoer the work-around you implemented in https://github.com/nodemcu/nodemcu-firmware/commit/7dd89dd15ef993c9740ba4d4361e6be8edd1284b is working for me!

**Comment by agjohnson** [comment] 2017-10-28 00:44
The latest mkdocs (0.17) removes the json output feature RTD relies on to index, so builds are broken completely with the latest version. It would be great to get someone that knows more about mkdocs maintaining these pieces, we don't have the bandwidth.

Raised in #3174

**Comment by marcelstoer** [comment] 2017-10-28 11:40
That is odd because earlier in this issue @d0ugal stated

> We have deprecated it in MkDocs but we won't remove it while RTD still depends on it.

**Comment by d0ugal** [comment] 2017-10-28 13:00
I don’t have the bandwidth for MkDocs now. So I guess that goal stopped with me. I’d recommend pinning at the previous release for now.

**Comment by virtualtam** [comment] 2018-04-03 22:03
Hi,

This issue seems to have been fixed (and/or worked around) by #3361 and #3496, I can confirm the ReadTheDocs search module works properly with MkDocs for the [Shaarli Documentation](https://shaarli.readthedocs.io/en/master/) (ref. https://github.com/shaarli/Shaarli/issues/1033)

Thanks @d0ugal, @ericholscher and @humitos :)

**Comment by humitos** [comment] 2018-04-04 00:16
@virtualtam I'm not very into mkdocs nor search, but, does your last comment mean that we need to close this issue or there is something else missing to track here?

(thanks for the update, though!)

**Comment by virtualtam** [comment] 2018-04-04 07:31
@humitos from a user's perspective, the search feature works for documentation generated with MkDocs and hosted on RTD, so I would suggest closing this issue (unless further changes are needed).

**Comment by davidfischer** [comment] 2018-06-01 18:50
It sounds like this is resolved.

**Comment by safwanrahman** [comment] 2018-08-07 18:13
I believe this Issue should be open as we are not indexing MkDocs in Elasticsearch index.

**Comment by stsewd** [comment] 2018-08-07 18:28
But it uses the default search from mkdocs (I think this issue was about the search in the docs, not in the rtd.org site?)

**Comment by safwanrahman** [comment] 2018-08-07 18:34
@stsewd Yeah. currently it uses built in search of mkdocs. But it would be better if we could index the content to our elasticsearch index so we can provide better search result to our users.

**Comment by stsewd** [comment] 2018-08-07 18:46
@safwanrahman maybe this interest you https://github.com/rtfd/readthedocs.org/issues/4205

**Comment by humitos** [comment] 2018-08-07 19:34
> But it would be better if we could index the content to our elasticsearch index so we can provide better search result to our users

IIRC, the problem we have with MkDocs is there is no way to generate a context to create the `.json` file as we do with Sphinx. The limitation was on MkDocs side, not on us.

I may be wrong, though.

**Comment by safwanrahman** [comment] 2018-08-07 19:37
@humitos The json file is created with the HTML file by default. But the structure is different. We need to port the json file to be indexed into our Elasticsearch.

**Comment by ericholscher** [comment] 2018-08-07 19:40
We need a way to dump mkdocs HTML unthemed, which is the main problem. It needs to be consistent across themes and builds.

**Comment by stsewd** [comment] 2019-01-10 16:41
This is still valid, but blocked and/or needs a design decision

**Comment by humitos** [comment] 2019-01-10 18:08
This issue is related to https://github.com/rtfd/readthedocs.org/issues/4588

**Comment by stsewd** [comment] 2020-04-29 00:03
This isn't fully closed. We are going to be indexing search data for mkdocs since next week, but not yet overriding the mkdocs search for ours.

**Closed** 2020-06-04 06:14 UTC
Labels: Accepted, Improvement

**Comment by stsewd** [comment] 2020-06-04 06:17
Hopefully this is going live next week, if someone wants to try the server side search for mkdocs projects next week, let us know via email at support@readthedocs.org.

**Comment by marcelstoer** [comment] 2020-06-04 06:29
What are the changes MkDocs-based projects have to make to be compliant with what goes live next week? Or maybe, which work-arounds have to/can be removed next week?

**Comment by stsewd** [comment] 2020-06-04 15:15
Let me explain this a little more. We used to index search data only for sphinx projects, but now we index search data for mkdocs too (search works here now https://readthedocs.org/projects/mkdocs-clone/search/?q=test&type=file&project=mkdocs-clone&version=latest for example).

With the other change (to be released next week), now you can get those results inside the doc pages. It should work with all mkdocs themes that have the `#mkdocs-search-results` and `mkdocs-search-query` elements. For now, you'll need to trigger a re-build for all versions you want search enabled after we enable the feature for your project. After the beta, you should be able to just use the server side search in all projects without needing to re-build

**Comment by stsewd** [comment] 2020-06-09 18:48
If someone is curious, this is how it looks

- https://mkdocs-clone.readthedocs.io/en/latest/
- https://mkdocs-test-stsewd.readthedocs.io/en/latest/search.html?q=versions

If you want to test this let us know via email at support@readthedocs.org.
