### ISSUE TITLE
Builds use a smaller builder when moving from pip to conda

### ISSUE THREAD

**Issue by chrisburr** [readthedocs/readthedocs.org#8004] opened 2021-03-11 07:53 UTC
## Details

* Read the Docs project URL:
    * New: https://readthedocs.org/projects/cburrdirac/
    * Upstream: https://readthedocs.org/projects/dirac/
* Build URL (if applicable):
    * New: https://readthedocs.org/projects/cburrdirac/builds/13209839/
    * Upstream: https://readthedocs.org/projects/dirac/builds/13209708/
* Read the Docs username (if applicable): chrisburr

We decided to try enabling the `conda` for the build environment for our docs so we could avoid mocking dependencies and remove the duplication between the tests and docs setup. I developed this by making a new project on readthedocs to build documentation using [my fork](https://readthedocs.org/projects/cburrdirac/) and then opened a PR to the [main repository](https://readthedocs.org/projects/dirac/). Surprisingly the builds now always fail with memory errors or timeouts.

It seems like the small build nodes are being used instead of the larger conda compatible ones. I've done some digging and it seems like #7912/#7933 added a feature to "lock" external builds to the queue used for the latest build:

https://github.com/readthedocs/readthedocs.org/blob/7450d6d36376f3372173729604a2edad239deb85/readthedocs/builds/tasks.py#L85-L104

I'm not sure how easy this is to fix. If it's difficult perhaps the easiest solution is to document this quirk [in the conda troubleshooting section](https://github.com/readthedocs/readthedocs.org/blob/d3b4f4796490cac9ff5d1fd64876d31ddb8b4c3c/docs/guides/conda.rst#troubleshooting). I'm happy to make a PR for the docs if that's the way you want to go.

## Expected Result

Builds in a copied repository work the same as in the original one.

## Actual Result

Moving to the upstream repository caused builds to fail.

**Comment by stsewd** [comment] 2021-03-11 15:08
Hi, looks like both builds are using the same build (big builders). Looks like this is due to an error on the build rather than a memory issue.

> grep: _build/html/CodeDocumentation: No such file or directory

**Comment by chrisburr** [comment] 2021-03-11 15:41
@stsewd Are you looking at https://readthedocs.org/projects/dirac/builds/13216630/? If so that was intentionally a test to bypass the logic I linked above and shorten the the amount of time the build would take.

I'm fairly sure the build I linked in the original post (https://readthedocs.org/projects/dirac/builds/13209708/) must have ran on a small builder as it failed with "Command killed due to excessive memory consumption".

**Comment by stsewd** [comment] 2021-03-11 16:25
Hmm, yeah, that one run on a smaller builder. Not sure how I ended up in the other build.

> If it's difficult perhaps the easiest solution is to document this quirk in the conda troubleshooting section. I'm happy to make a PR for the docs if that's the way you want to go.

the docs already mention to contact us to increase resources in case of problems.

So, the problem is with our task router, yeah. We could move the conda check before doing the external build check. /cc @humitos.

**Comment by humitos** [comment] 2021-03-15 12:01
This is an edge case and I'm not sure how to solve it. We use historical builds data to know which would be the best queue to build the current build. At this point we don't have the `build.config` attribute, so we rely on previous build to decide which one to use. At that point, previous builds were using `build:default` queue but the current build is using `conda` so it should use `build:large`, but I don't know how we would know that.

I think we should mark this project to use `build:large` queue and close this issue.

> NOTE that after a couple of failed builds for a regular Version it will start using `build:large` again for regular Versions but also for Pull Request since we will have some data for `build.config`: https://github.com/readthedocs/readthedocs.org/blob/7450d6d36376f3372173729604a2edad239deb85/readthedocs/builds/tasks.py#L111

**Closed** 2021-03-29 11:31 UTC
Labels: Improvement
