### ISSUE TITLE
Database RemoreRepository inconsistent data: multiple objects returned at `.get`

### ISSUE THREAD

**Issue by remram44** [readthedocs/readthedocs.org#5351] opened 2019-02-25 18:56 UTC
## Details

* Read the Docs project URL: N/A
* Build URL (if applicable): N/A
* Read the Docs username (if applicable): remram

## Expected Result

A list of repositories on https://readthedocs.org/dashboard/import/

## Actual Result

Every time I visit the page, there are no repositories. I can see my name and only one of my organizations on the right (I am actually in 12 organizations).

When I click the refresh icon (two arrows in circle) I see an error message in red:

> There was an error with your request: get() returned more than one RemoteRepository -- it returned 2!

Seems similar to #2613 #1864 (both closed)

**Comment by stsewd** [comment] 2019-02-25 22:45
I'll take a further look later, but maybe it's the same as https://github.com/rtfd/readthedocs.org/issues/4818

**Comment by stsewd** [comment] 2019-03-06 00:23
Sentry issue https://sentry.io/organizations/read-the-docs/issues/910559197/?project=148442&query=is%3Aunresolved+it+returned+2&statsPeriod=14d&utc=false

**Comment by stsewd** [comment] 2019-03-06 00:32
Ok, that wasn't the related sentry issue, I don't think we are logging that to sentry.

Maybe did you integrated two github accounts to your rtd account?

**Comment by remram44** [comment] 2019-03-06 00:39
I only have one GitHub account though. I do I check and/or correct this?

**Comment by remram44** [comment] 2019-03-20 17:56
Today I noticed that my repository list was updated (showing thousands of repository because I'm in conda-forge) but still clicking on the refresh button shows:

> There was an error with your request: get() returned more than one RemoteRepository -- it returned 2!

**Comment by dojutsu-user** [comment] 2019-05-04 18:19
Still valid.... I think.

**Comment by remram44** [comment] 2019-06-18 18:53
Why mark issues as stale if you're the ones not addressing them?

**Comment by stsewd** [comment] 2019-06-18 19:34
That's automatic, it's hard to find the problem if we can't replicate it locally.

**Comment by remram44** [comment] 2019-08-02 20:35
This is really offensive. Makes me think that you don't care about users at all and are just waiting for them to go away.

**Comment by remram44** [comment] 2019-08-02 20:35
Having me re-state every month that yes I would still like you to look into my problems is really not cool.

**Comment by stsewd** [comment] 2019-08-02 21:02
There isn't much we can do if we are not able to replicate the problem locally. The stale label is done by a bot, not from the read the docs team.

You can try to import your problem manually from here https://readthedocs.org/dashboard/import/manual/

**Comment by remram44** [comment] 2019-08-02 21:09
The robot was put in place by the Read The Docs team. Of course I'm not blaming the robot.

I don't understand how you can fail to reproduce that given you have access to the database. I don't know what step I can take to make this more reproducible. I gave you the ID of the account (mine) where this happens, you can do this get request and see what happens.. I cannot give more details apart from the error I see, but you can read the server's logs. If you won't do that we are at an impasse but it's only because you won't take any step to move forward, not because the steps don't exist.

**Comment by remram44** [comment] 2019-08-02 21:10
See you next month when your bot tells me my issue doesn't matter anymore, and I have to come back and say that it does to me.

**Comment by humitos** [comment] 2019-08-02 23:48
Hey @remram44! We do Read the Docs with love. It's an OSS project and we also work on our free time to make it better. I suggest you to avoid any kind of message similar to the ones you wrote here.

We have a roadmap to follow. Our time is limited and we need to focus on the work that makes Read the Docs to keep working as is: free and open.

We do care about users, but here, it seems that _you_ don't care about _us_. So, please stop these comments. Nobody want to read them.

**Comment by humitos** [comment] 2019-08-02 23:50
Now, regarding your problem. It seems that one of the duplicated repositories in our DB is `conda-forge/r-expsmooth-feedstock`. This is definitely an inconsistency in our database that we need to clean up. I'm not sure how we get there yet, but I will probably have more information after research a little more and once you have said "I'm sorry" :)

**Comment by humitos** [comment] 2019-08-03 00:17
Actually, for the records and when we come back to debug this, there are 2266 `RemoteRepository` duplicated for this user. Probably, just removing them and re-sync is the solution here.

**Comment by remram44** [comment] 2019-08-03 00:19
Thank you for taking a look. Would you consider removing the stale bot, which does nothing for your users or your image?

**Comment by humitos** [comment] 2019-08-03 11:16
> Would you consider removing the stale bot, which does nothing for your users or your image?

Thanks for the suggestion. We are not consider removing the bot for now.

I removed "Needed: replication" and marked the issue as "Accepted" now that we know the reason of this.

I also changed the title of the issue to be more descriptive.

**Comment by humitos** [comment] 2019-08-03 11:16
This is the chunk of code that returns multiple objects,

https://github.com/readthedocs/readthedocs.org/blob/ef48c975fc003d2067625f4090bc791f11d0641c/readthedocs/oauth/services/github.py#L92-L96

**Comment by humitos** [comment] 2019-08-12 15:24
Hey @remram44! I think I fixed your issue.

Please go to https://readthedocs.org/dashboard/import/ and re-sync your social accounts clicking on the small arrows button.

Let me know if it works.

**Comment by remram44** [comment] 2019-08-12 16:57
Great news, thanks @humitos! I started the process, but it has been going for 5+ minutes. I will report back later.

I assume this is all because of the huge number of repositories in the conda-forge organization. Maybe there should be a way to prevent ReadTheDocs from enumerating repositories in specific organizations? (or you could blacklist this one since it is very much a special case, it has over 7000 repositories)

**Comment by remram44** [comment] 2019-08-12 17:31
It worked! Thank you so much @humitos. I don't know if the issue that made this happen was fixed, so I'll leave this for you to close (or not), but as far as I can see my problem is solved.

Thanks again!

**Comment by humitos** [comment] 2019-08-12 17:46
Thanks! We believe the root cause of this is fixed and it seems that you were the only user hitting this problem. I will close it and we can revisit if it re-appears, but I don't think so.

**Closed by humitos** 2019-08-12 17:46 UTC
Labels: Accepted, Bug
