### ISSUE TITLE
Requests by Google(bot) will be answered with 403 Forbidden by Cloudflare

### ISSUE THREAD

**Issue by msbt** [readthedocs/readthedocs.org#8274] opened 2021-06-21 13:27 UTC
## Details

We registered a recent drop in traffic and checked the Search Console for pointers, apparently Google is no longer allowed to fetch the various sitemaps and content of our RTD repositories. The requests result in 403 errors and it says "Couldn't fetch" in the overview and this in the "details" (which is not very conclusive, especially if opening the sitemap works on all our machines):

Pages:
![grafik](https://user-images.githubusercontent.com/8767096/122769415-d3835080-d2a4-11eb-839f-2045b1ec98e3.png)

Sitemaps:
![grafik](https://user-images.githubusercontent.com/8767096/122761910-0d505900-d29d-11eb-9f62-ae4c45176284.png)

Only when you add `-A "googlebot"` or its derivatives in the curl request, it also throws a 403 error (might be unrelated due to the way googlebots and the corresponding ip addresses work, but I thought I would mention it).

Like so:
```
$ curl -A "googlebot" --head https://crate.io/docs/crate/reference/en/latest/sitemap.xml
HTTP/2 403
```

Can anyone confirm a similar issue on their sitemaps?

* Read the Docs project URL: https://crate.readthedocs.io/en/latest/sitemap.xml / https://crate.io/docs/crate/reference/en/latest/sitemap.xml (reverse proxied)
* Build URL: https://readthedocs.org/projects/crate/builds/

## Expected Result

Google fetching our sitemaps as they used to.

## Actual Result

Fetching blocked by 403 errors.

**Comment by msbt** [comment] 2021-06-21 14:05
Also tried other doc-examples to rule out issues within our environment:

`curl --user-agent "Mozilla/5.0 (compatible; foobar/2.1; +http://www.google.com/)" https://docs.phpmyadmin.net/en/latest/intro.html`

**Comment by stsewd** [comment] 2021-06-21 14:34
Thanks for reporting this! We enabled our cloudflare firewall some weeks ago when we were being hit by a DDOS attack, the firewall may be blocking more than we want.

**Comment by ericholscher** [comment] 2021-06-21 14:43
I'm guessing most of the blocking was because CF knows that you aren't connecting from a Google IP, and it's blocking people using their user agent in a fake manner. However, actually blocking Google is bad. We've turned off the Bad Bots filter, and the requests are 200'ing for me, so hopefully that will fix it.

**Comment by ericholscher** [comment] 2021-06-21 14:48
Hrm, looking at it more, I'm still getting 403's sometimes. It looks like some weird requests are hitting our servers, and I see a bunch of traffic being served by Varnish. Are y'all proxying back to our docs in some fashion? I'm guessing that might also be causing other issues, and you should configure the docs according to our guide to avoid any additional problems: https://docs.readthedocs.io/en/latest/custom_domains.html#custom-domain-support

**Comment by ericholscher** [comment] 2021-06-21 14:54
For example, I don't see any hits in our firewall logs for `crate.io`, which makes this issue really difficult to debug. I'm guessing you're proxying to some other domain based on our old header-based setup, but we don't recommend this approach and it's deprecated.

**Comment by amotl** [comment] 2021-06-21 14:59
Hi there,

thanks a stack for your quick response.

> We've turned off the Bad Bots filter, and the requests are 200'ing for me, so hopefully that will fix it.

I can confirm it now works on the URL for the CrateDB docs as outlined by @msbt.

```shell
$ curl --user-agent "googlebot" --head https://crate.io/docs/crate/reference/en/latest/sitemap.xml
HTTP/2 302
```

However, it doesn't work yet on the phpMyAdmin docs.

```shell
$ curl --user-agent "googlebot" --head https://docs.phpmyadmin.net/en/latest/intro.html
HTTP/2 403
```

> I'm guessing most of the blocking was because CF knows that you aren't connecting from a Google IP, and it's blocking people using their user agent in a fake manner.

Exactly. That's also what @norosa suggested, see [1,2].

> Are y'all proxying back to our docs in some fashion? I'm guessing that might also be causing other issues, and you should configure the docs according to our guide to avoid any additional problems: https://docs.readthedocs.io/en/latest/custom_domains.html#custom-domain-support

Right, I also suggested to let us (CrateDB) have a review one those details, thanks! Specifically, I was looking at the `X-Real-IP` header here. If the reverse proxy on `crate.io` would not propagate this header to RTD appropriately, it would be no wonder that CF would trip those protections because it would not have a chance to identify the origin of googlebot appropriately.

We will look into this and report back about the outcome. Thank you again for linking to the respective page of the RTD documentation [3] and for the quick turnaround by disabling the Bad Bots filter for now.

With kind regards,
Andreas.

[1] https://community.cloudflare.com/t/cloudflare-managed-special-rules-are-blocking-googlebot/82911
[2] https://community.cloudflare.com/t/cloudflare-firewall-blocking-legitimate-google-bing-bots/144763
[3] https://docs.readthedocs.io/en/latest/custom_domains.html#custom-domain-support

**Comment by msbt** [comment] 2021-06-21 15:00
Thanks for checking it out, I'll investigate and get back to you. And you're right, we're using fastly as our entrypoint, but reverse-proxy requests to the docs via nginx to crate.io. It's odd though, varnish (as in Fastly) shouldn't be active at that stage.

**Comment by ericholscher** [comment] 2021-06-21 15:00
I've also disabled the WAF from the `crate.io` domain to keep things working for now -- let me know if you'd like me to turn it back on to test another setup here soon.

**Comment by ericholscher** [comment] 2021-06-21 15:01
Yea, the `phpmyadmin` thing is more worrisome -- I'm going to keep looking into that one.

**Comment by ericholscher** [comment] 2021-06-21 15:04
I think the other useful next step here would be asking CF support about the actual Googlebot requests getting blocked -- that is a real issue. I'll follow up with them.

**Comment by amotl** [comment] 2021-06-21 15:05
All right, thank you!

Apparently, the `curl` request only was succeeding on a page which would yield a 302 redirect. On a regular page, we still get

```shell
$ curl --user-agent "googlebot" --head https://crate.io/docs/crate/reference/en/4.5/sitemap.xml
HTTP/2 403
```

> It appears those are getting blocked by 100201 - Anomaly:Header:User-Agent - Fake Google Bot -- which seems right :)

Yeah, it definitively feels right, now that we know about the origin of the "problem" - it's actually a feature ;]! So, let us have a review on our Nginx settings at crate.io together with @WalBeh, we will come back here and report afterwards. Thanks again for taking the time!

> I think the other useful next step here would be asking CF support about the _actual_ Googlebot requests getting blocked -- that is a real issue. I'll follow up with them.

Right. Thank you _so_ much!

**Comment by amotl** [comment] 2021-06-21 15:46
Hi again,

I took a look at our Nginx configuration and wanted to share the outcome with you.

### Report
Hereby, I am sharing the current Nginx configuration snippet we use for reverse-proxying specific sections of crate.io/docs to RTD.

```nginx
location ~ ^/docs/crate/reference/(.*)$ {
    proxy_pass https://crate.readthedocs.io:443/$1;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Scheme $scheme;
    proxy_set_header X-RTD-SLUG crate;
    proxy_intercept_errors on;
    add_header Surrogate-Control max-age=2592000;
    add_header Surrogate-Key "docs docs/crate docs/crate/reference";
    expires 4h;
    break;
}
```

There are  individual snippets like that for the different projects we host individually on RTD. Modulo respective settings for `location`, `X-RTD-SLUG` and `Surrogate-Key`, they are all the same.

```nginx
location ~ ^/docs/crate/tutorials/(.*)$ {
    proxy_pass https://crate-tutorials.readthedocs.io:443/$1;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Scheme $scheme;
    proxy_set_header X-RTD-SLUG crate-tutorials;
    proxy_intercept_errors on;
    add_header Surrogate-Control max-age=2592000;
    add_header Surrogate-Key "docs docs/crate docs/crate/tutorials";
    expires 4h;
    break;
}
```

### Evaluation
There is definitively a difference to the canonical snippet you shared at [Custom Domains and White Labeling » Proxy SSL](https://docs.readthedocs.io/en/latest/custom_domains.html#proxy-ssl).

```nginx
location / {
    proxy_pass https://pip.readthedocs.io:443;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Scheme $scheme;
    proxy_set_header X-RTD-SLUG pip;
    proxy_connect_timeout 10s;
    proxy_read_timeout 20s;
}
```

Specifically, I see the `Host` header is not set in our configuration settings. Furthermore, `$scheme` is assigned to `X-Forwarded-Proto`, where your example explicitly uses `https`. Do you believe those anomalies could be a valid trace to the problem and that it would be crucial to get them straight before being able to further investigate anything else?

With kind regards,
Andreas.

**Comment by amotl** [comment] 2021-06-22 17:54
Dear Eric and Manuel,

at https://github.com/readthedocs/readthedocs.org/issues/8274#issuecomment-865098343, you wrote:

> I'm guessing you're proxying to some other domain based on our old header-based setup, but we don't recommend this approach and it's deprecated.

Just out of curiosity: Do you refer to that kind of reverse-proxying configuration we shared above to being deprecated? If so, how else would we achieve such a configuration where different kinds of URL paths are routed to different projects on RTD?

Some examples for us are:
- https://crate.io/docs/crate/reference/
- https://crate.io/docs/crate/tutorials/
- https://crate.io/docs/crate/howtos/
- https://crate.io/docs/python/

Apologies if we didn't follow recent updates to RTD's infrastructure, features and policies appropriately. Our documentation setup has been conceived some years ago already and since then chugging along, so that, for example, we only recently started upgrading to Sphinx 3/4. We will be happy to take any needed changes related to RTD into account.

Thank you for taking the time to educate us on this matter. 

With kind regards,
Andreas.

**Comment by stsewd** [comment] 2021-06-22 18:01
@amotl we have a "subprojects" feature that allows you to serve multiple projects on the same domain https://docs.readthedocs.io/en/stable/subprojects.html, but the URLs would be something like `crate.io` (main project is served from here)  `crate.io/projects/reference`, `crate.io/projects/python`. You can be able to redirect those old paths to the new ones if you decide to change them https://docs.readthedocs.io/en/stable/user-defined-redirects.html

**Closed** 2021-08-19 23:11 UTC
Labels: Needed: more information
