### ISSUE TITLE
"build.tools.python" expected one of (... 3 ...), got 3

### ISSUE THREAD

**Issue by akosthekiss** [readthedocs/readthedocs.org#10800] opened 2023-10-05 08:36 UTC
## Details

* Read the Docs project URL: https://readthedocs.org/projects/grammarinator/
* Build URL (if applicable): https://readthedocs.org/projects/grammarinator/builds/22120857/

## Expected Result

A correct build after updating the config file to include `build.os` and `build.tools.python`, as mandated by https://blog.readthedocs.com/use-build-os-config/ .

## Actual Result

Build failed

Error

Problem in your project's configuration. Invalid configuration option "build.tools.python": expected one of (2.7, 3.6, 3.7, 3.8, 3.9, 3.10, 3.11, 3, miniconda3-4.7, mambaforge-4.10, mambaforge-22.9), got 3

**Comment by stsewd** [comment] 2023-10-05 19:32
Hi, this is a duplicate of https://github.com/readthedocs/readthedocs.org/issues/9719, please put the number in quotes to make it work (3 -> "3").

**Closed by stsewd** 2023-10-05 19:32 UTC
