### ISSUE TITLE
403 when pulling additional files from github via "rawusercontent" URL

### ISSUE THREAD

**Issue by AKuederle** [readthedocs/readthedocs.org#11769] opened 2024-11-14 15:53 UTC
## Details

* Read the Docs project URL: https://app.readthedocs.org/projects/mobgap/
* Build URL (if applicable): https://app.readthedocs.org/projects/mobgap/builds/26276495/

My build downloads some additional files from a secondary github repo using `raw.githubusercontent.com` URLs. For example in the build above the file `https://raw.githubusercontent.com/mobilise-d/mobgap_validation/main/results_file_registry.txt`.
This is done using the Python requests library (acutally I am using [pooch](https://www.fatiando.org/pooch/latest/api/generated/pooch.HTTPDownloader.html) which uses requests under the hood).

This worked fine when I first tested it, but at some point I was getting 403s (Last build that succeeded: https://app.readthedocs.org/projects/mobgap/builds/26255329/). I assumed that I might have hit some type of rate limit, but even after waiting for 24h+ the error remains.

Running the build locally and in the Github CI works, so it seems to be specific to the RTD infrastructure.

**Comment by humitos** [comment] 2024-11-14 17:03
Duplicate of #11763. Please subscribe there or add more details.

**Closed by humitos** 2024-11-14 17:03 UTC
