### ISSUE TITLE
Better message for memory limit errors

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#3613] opened 2018-02-15 02:11 UTC
## Details

In some cases the build fails due to memory limits, but there isn't a clear message of what happened (I think I see some few projects with the correct message, or maybe none?).

See #3031, #3603, #3612, #3580

## Expected Result

A message about memory limit is shown.

## Actual Result

A plain message "Build failed" is shown.

I'm not sure if we can catch this types of errors on the environment.

**Comment by humitos** [comment] 2018-03-07 04:11
We have some code written to try to catch this at 

https://github.com/rtfd/readthedocs.org/blob/78b5781ad071de656451a262d39458c612c45be0/readthedocs/doc_builder/environments.py#L245-L253

but the problem is that even on a memory limit reached sometimes that exit code is not properly returned and some random things happened. Actually, I think that I added that look for `killed` in the output because of this issue.

Due those random situations is that we don't have a good solution yet.

**Comment by humitos** [comment] 2019-07-18 16:34
I think we can close this issue for now since there is not much else we can do to catch _when_ a memory limit was reached.

If we have a plan to reach this goal, we should write it down here and re-open the issue.

**Closed by humitos** 2019-07-18 16:34 UTC
Labels: Accepted, Improvement
