### ISSUE TITLE
enable billing annually rather than monthly

### ISSUE THREAD

**Issue by bowenli86** [readthedocs/readthedocs.org#6943] opened 2020-04-21 20:55 UTC
## Details

read the docs should be able to bill users annually rather than monthly. I have to keep track of lots of receipts over the time, which is quite annoying

## Expected Result

read the docs should be able to bill users annually rather than monthly. 

## Actual Result

read the docs bill users monthly.

**Comment by humitos** [comment] 2020-04-22 10:22
Hi @bowenli86! Do you refer to Gold Membership?

**Comment by bowenli86** [comment] 2020-04-22 17:03
> Hi @bowenli86! Do you refer to Gold Membership?

Hi @humitos yes!

**Comment by ericholscher** [comment] 2020-04-29 16:50
This is a duplicate of #6279. We can track it there.

**Closed by ericholscher** 2020-04-29 16:50 UTC
Labels: Accepted
