### ISSUE TITLE
Failed to build chinese docs: Build output directory for format "pdf" contains multiple files ...

### ISSUE THREAD

**Issue by jhj0411jhj** [readthedocs/readthedocs.org#10132] opened 2023-03-09 08:38 UTC
## Details

* Read the Docs project URL: https://readthedocs.org/projects/open-box-zh-cn/
* Build URL (if applicable): https://readthedocs.org/projects/open-box-zh-cn/builds/19722444/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/jhj0411jhj/
* Github commit history: https://github.com/PKU-DAIR/open-box/commits/master

## Expected Result

*A description of what you wanted to happen*

I use readthedocs for our github project [openbox](https://github.com/PKU-DAIR/open-box). The english version docs has no problem. The chinese version docs fails to build since Feb 9, 2023 (last successful build time is Jan 30, 2023. first failed build time is Feb 9, 2023. Maybe there are some updates in readthedocs).

Then I tried to build the chinese docs from the commit that triggered a successful build in the past, but the build process failed.

+ The same commit I use: https://github.com/PKU-DAIR/open-box/commit/c7385e957f457f6c4396ac372bdf36106d27fbaf
+ Past successful build: https://readthedocs.org/projects/open-box-zh-cn/builds/18949012/
+ Failed build: https://readthedocs.org/projects/open-box-zh-cn/builds/19722444/

## Actual Result

*A description of what actually happened*

Error message:
```
Build output directory for format "pdf" contains multiple files and it is not currently supported. Please, remove all the files but the "pdf" your want to upload.
```

**Comment by humitos** [comment] 2023-03-09 08:44
Hi! This is duplicate of #10015. The issue here is that your `latexmk` command is failing. The error message is wrong and it will be fixed in the next deploy.

You need to fix your PDF generation for the build to succeed or disable it.

**Comment by jhj0411jhj** [comment] 2023-03-09 09:36
> @humitos Thanks. I have tried to **disable PDF generation** in readthedocs project settings (and EPUB is enabled). However, I found in the build process, `cat latexmkrc` and `latexmk -r latexmkrc -pdf -f -dvi- -ps- -jobname=open-box-zh-cn -interaction=nonstopmode` were still executed, so the build was failed.

I disabled PDF generation and a new build was triggered automatically, then failed in building PDF. Should I push a new commit to my github repo and trigger a new build process, so disabling PDF generation will take effect?

**Comment by humitos** [comment] 2023-03-09 11:04
Your project is using a config file, so you have to remove the PDF format from https://github.com/PKU-DAIR/open-box/blob/master/.readthedocs.yml#L18

**Comment by jhj0411jhj** [comment] 2023-03-09 14:28
@humitos Thanks!

**Closed** 2023-03-09 15:00 UTC
Labels: Support, Needed: more information
