### ISSUE TITLE
De-duplicate the LatexBuilders

### ISSUE THREAD

**Issue by ericholscher** [readthedocs/readthedocs.org#2216] opened 2016-05-17 23:46 UTC
Ended up hacking the LatexBuilder in the Sphinx.py builder file, so that it has two concrete subclasses. This is not optimal, and we should make it nicer. 

https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/doc_builder/backends/sphinx.py#L239-L260

**Comment by humitos** [comment] 2017-02-23 20:43
I'm not sure to understand why you duplicate it. Why not just use the same class?

What's the different behavior you want to have in each of those classes?

**Comment by ericholscher** [comment] 2017-02-23 20:49
The docker subclass is used when we're building with Docker. It's set here: https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/doc_builder/backends/sphinx.py#L307-L310 -- there is likely a better way to handle this with a bit more logic somewhere.

**Comment by stsewd** [comment] 2018-01-02 03:38
What I understand here is that one class is used to run the build command on local environment and the other on a docker environment. All this logic is decided from here https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/projects/tasks.py#L240-L252.

I think remember someone saying that support for local builds isn't going to be maintained anymore (maybe I just making it up), it's that correct?

**Comment by humitos** [comment] 2019-07-18 15:44
This issue talks about [LatexBuildCommand](https://github.com/rtfd/readthedocs.org/blob/7be01d844b981635822d4df73f614ad2c3d71b8b/readthedocs/doc_builder/backends/sphinx.py#L374) and [DockerLatexBuildCommand](https://github.com/rtfd/readthedocs.org/blob/7be01d844b981635822d4df73f614ad2c3d71b8b/readthedocs/doc_builder/backends/sphinx.py#L386)

I'm marking this as Good First Issue to receive a contribution here.

**Comment by krptic07** [comment] 2019-11-10 03:47
I want to take up this issue. Can anybody explain it to me, what i need to do?

**Comment by astrojuanlu** [comment] 2021-09-02 14:04
If I understand correctly, the problem is that `doc_builder.backends.sphinx.LatexBuildCommand` and `doc_builder.backends.sphinx.DockerLatexBuildCommand` do exactly the same, am I right? Can we indeed clarify what do we intend here?

**Comment by humitos** [comment] 2023-09-15 14:08
I'm closing this issue because we _need_ these two classes while supporting local builds (for tests) and docker builds. There is nothing we can do at this time to remove/merge these two classes.

**Closed by humitos** 2023-09-15 14:08 UTC
Labels: Good First Issue, Improvement, Accepted
