### ISSUE TITLE
"Server side search" gets an not-useful wall of text

### ISSUE THREAD

**Issue by rfay** [readthedocs/readthedocs.org#9419] opened 2022-07-07 19:23 UTC
## Details

* Read the Docs project URL: https://readthedocs.org/projects/test-ddev/
* Build URL (if applicable): https://readthedocs.org/projects/test-ddev/builds/17382495/
* Read the Docs username: https://readthedocs.org/profiles/ddev/

* Source: https://github.com/rfay/ddev/tree/20220707_docs2

## Expected Result

Simple and appropriate search results. This is what I see with `mkdocs serve`:

<img width="977" alt="Cursor_and_Get_Started_with_DDEV_-_DDEV-Local_Documentation" src="https://user-images.githubusercontent.com/112444/177855523-99865975-58e6-4183-8fc6-641c91e8b0cf.png">

## Actual Result

On RTD at https://readthedocs.org/projects/test-ddev/ I get a huge wall of text that's completely not useful:

<img width="987" alt="Get_Started_with_DDEV_-_DDEV-Local_Documentation" src="https://user-images.githubusercontent.com/112444/177855691-d0465fb9-dfbb-40a1-935f-55fa1d5b4bc2.png">

I assume this is a result of [Server side search](https://docs.readthedocs.io/en/stable/server-side-search.html) because I get very decent results with `mkdocs serve`. 

Is there a way to disable server-side search or fix this somehow?

**Comment by stsewd** [comment] 2022-07-07 19:43
Hi, Server Side Search isn't integrated into mkdocs by default, what you are seeing is the mkdocs search.
When you build locally, make sure you are using the same version of mkdocs as the one used on rtd, which is this one https://github.com/rfay/ddev/blob/20220707_docs2/docs/mkdocs-pip-requirements#L15

**Comment by rfay** [comment] 2022-07-07 20:45
Thanks for your help.  Yes, using the exact same version of mkdocs, 1.3.0. What else could be different? It's quite dramatic.

**Comment by stsewd** [comment] 2022-07-07 21:38
@rfay I built your docs locally on a clean environment, and I was able to replicate the problem.

```
pip install -r docs/mkdocs-pip-requirements
python -m mkdocs build
```

![Screenshot from 2022-07-07 16-37-04](https://user-images.githubusercontent.com/4975310/177875616-8c3cd7fd-bd5c-45a4-b374-d601d700c554.png)

I'm closing this issue since isn't a problem related to rtd.

**Closed by stsewd** 2022-07-07 21:38 UTC
Labels: Support

**Comment by rfay** [comment] 2022-07-07 22:30
You're exceptionally kind to take the time to do that.

I just recreated your steps and have it perfect locally and horrible on RTD. I'll try on an amd64 machine. Do I need to have an ancient version of python or something? I have Python 3.9.13

**Comment by rfay** [comment] 2022-07-07 22:36
I was able to recreate the issue with a clean build on gitpod.io, so I agree, not related to RTD, may be something about amd64 vs arm64 or linux vs macOS, not sure. I'll chase. Thanks so much for taking the time to engage on this.

**Comment by rfay** [comment] 2022-07-08 22:25
The problem here was that I had moved to use mkdocs-material-insiders, then (tried to) back that out. I apparently hadn't been fully successful, and the machines I was testing on already had pip-installed mkdocs-material-insiders on them, so they worked, even though that wasn't in the requirements file. 

Thanks so much for the help.

**Comment by squidfunk** [comment] 2022-07-09 06:38
Author of Material for MkDocs here. This happens when you feed a `search_index.json` that was built with Insiders into the non-Insiders version of Material for MkDocs. Insiders features a [completely rewritten search plugin](https://squidfunk.github.io/mkdocs-material/blog/2021/search-better-faster-smaller/). You only have to make sure that you're not mixing inside the same environment (be it through caching or other means).

**Comment by squidfunk** [comment] 2022-07-09 06:48
@stsewd adding `must-revalidate` when serving `search_index.json` solves the problem. Also, it would mean that users will receive the new search index immediately after a deployment, and not after a day. It's current set to `max-age=86400`.

Unless there's a reason I don't see why data should be cached for so long. GitHub Pages uses `max-age=600`.

**Comment by stsewd** [comment] 2022-07-09 16:57
@squidfunk I was able to replicate this by just installing the requirements from https://github.com/rfay/ddev/blob/0c30dc1afb60172090ae98c64e5efe0a22fb2218/docs/mkdocs-pip-requirements in a clean environment (https://github.com/readthedocs/readthedocs.org/issues/9419#issuecomment-1178256031), so I don't think this related to serving an outdated search_index.json file.

**Comment by squidfunk** [comment] 2022-07-09 21:45
The `requirements.txt`only lists `mkdocs-material`, not Insiders. Thus, you're both likely describing different problems. If you can provide a minimal reproducible example, I'm happy to look into it.

**Comment by rfay** [comment] 2022-07-09 21:50
This is all solved, the real requirements now includes mkdocs-material-insiders again, and I'll figure out how to roll that back. The problem here was having mkdocs-material in the requirements, but having things in the mkdocs.yml that depended on insiders.

**Comment by squidfunk** [comment] 2022-07-09 21:52
[Our documentation](https://squidfunk.github.io/mkdocs-material/insiders/getting-started/#built-in-plugins) explains how you can build documentation with and without Insiders to support outside contributors.

**Comment by rfay** [comment] 2022-07-09 21:55
Yes, but not with the same features. For example, you'd have to leave out the search plugin.
