### ISSUE TITLE
rtd uses sphinx 1.8.5 even if it previously installed 2.2.0

### ISSUE THREAD

**Issue by ssbarnea** [readthedocs/readthedocs.org#6292] opened 2019-10-15 10:04 UTC
## Details

* Read the Docs project URL: https://github.com/pycontribs/jira/blob/master/.readthedocs.yml
* Build URL (if applicable): https://readthedocs.org/projects/jira/builds/9803343/
* Read the Docs username (if applicable): ssbarnea

## Expected Result

Successful build of docs using the requires sphinx 2.2.0.

## Actual Result

Based on the logs sphinx 2.2.0 is installed (docs extra) but after that I see:
```
python /home/docs/checkouts/readthedocs.org/user_builds/jira/envs/latest/bin/sphinx-build -T -E -b readthedocs -d _build/doctrees-readthedocs -D language=en . _build/html

 Running Sphinx v1.8.5
loading translations [en]... done

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/jira/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 303, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jira/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 215, in __init__
    'be built with this version.') % self.config.needs_sphinx)
sphinx.errors.VersionRequirementError: This project needs at least Sphinx v2.2.0 and therefore cannot be built with this version.

Sphinx version error:
This project needs at least Sphinx v2.2.0 and therefore cannot be built with this version.
```

Apparently the `sphinx-build` is called without activating the virtual environment, so failing

**Comment by humitos** [comment] 2019-10-15 11:24
You probably need to wipe the environment. Can you try that first? Thanks.

**Comment by stsewd** [comment] 2019-10-15 15:56
This looks like a cache problem, please try wiping the env before triggering a new build https://docs.readthedocs.io/en/stable/guides/wipe-environment.html

**Comment by matfax** [comment] 2019-10-20 14:48
This is probably a duplicate of #5810

**Closed** 2019-11-18 12:40 UTC
Labels: Needed: more information, Support
