### ISSUE TITLE
Upload externally build docs using API

### ISSUE THREAD

**Issue by leonardder** [readthedocs/readthedocs.org#5993] opened 2019-07-25 16:47 UTC
## Details
For the [NVDA screen reader project](https://www.nvaccess.org/), I'm investigating hosting our developer docs on read the docs. A problem for us however, is that NVDA only runs on Windows and is highly dependant on it running on Windows. For example, we have a module that defines a C structure that relies on a ctypes.wintypes.DWORD field, but we can't mock ctypes.wintypes properly.

I've investgiated using sphinx AutoAPI, but [that also has its issues for us](https://github.com/readthedocs/sphinx-autoapi/issues/169)

## Expected Result
As we're running our builds on appveyor, it would help if we could build our API docs and automatically upload them to read the docs in the process. Alternatively, it would help if rtd could build on Windows, but that's probably too far-fetched.

## Actual Result
As far as I've seen, this ability is not yet available.

**Comment by stsewd** [comment] 2019-07-25 16:49
Closing as duplicate of https://github.com/readthedocs/readthedocs.org/issues/1083

**Closed by stsewd** 2019-07-25 16:49 UTC
