### ISSUE TITLE
Non active but hidden versions are stuck in a redirect loop

### ISSUE THREAD

**Issue by NicolasMassart** [readthedocs/readthedocs.org#9485] opened 2022-08-09 12:51 UTC
## Details

* Read the Docs project URL: https://readthedocs.org/projects/hyperledger-besu/

Hi, was trying to figure out how to make a version inactive and have it redirect to the default (latest) version.
It seems that the behaviour is broken when the version is hidden. 
Currently when I uncheck the active box on a version but keep the hidden box checked, if I try to go to the version doc, it get stuck in a redirect loop and browser displays a "too many redirect" error.

This works well if both Active and Hidden are unchecked.

## Expected Result

Non active AND hidden versions should redirect to the default version.

Exemple: https://besu.hyperledger.org/en/1.5.0/Concepts/Privacy/Privacy-Overview/ -> https://besu.hyperledger.org/en/stable/Concepts/Privacy/Privacy-Overview/

## Actual Result

Non active AND hidden versions are stuck in a redirect loop. The page returns a 302 redirect to the same address.
Exemple https://besu.hyperledger.org/en/1.5.0/Concepts/Privacy/Privacy-Overview/ returns `ERR_TOO_MANY_REDIRECTS`

**Comment by humitos** [comment] 2022-08-09 14:27
Hi @NicolasMassart. Do you have set up a redirect?

I think this is a duplicate of #9335. I guess that Read the Docs is not deleting the HTML files from the storage when you mark a version as `active=False`, and I think it should. That would solve this issue, I guess.

**Comment by NicolasMassart** [comment] 2022-08-09 14:32
I have redirects but they should not interact with this I guess.
<img width="621" alt="redirects list screenshot" src="https://user-images.githubusercontent.com/4677568/183675998-07f603e3-310e-4837-8aba-9c3feff1bdcb.png">
Maybe it's a dup of the issue you linked. If so, feel free to close this one.

**Comment by humitos** [comment] 2022-08-09 14:38
Thanks for your quick reply. I don't think it's a problem with the redirects, yeah. I added the other issue as planned to the roadmap. Hopefully, we can prioritize it soon. Please, subscribe there to receive notifications.

**Comment by NicolasMassart** [comment] 2022-08-09 14:41
Also note that the use of hidden on an inactive version is totally useless. If it's inactive it not accessible even in a hidden way.
But as it generates a bug, I wanted to make sure we know.
On my side I changed all the inactive versions hidden status to false with the API (except the one linked in this issue as example). So I'm good, no blocker.

**Comment by humitos** [comment] 2022-08-09 17:41
> Also note that the use of hidden on an inactive version is totally useless

You have a point here 👍🏼 . This should not be allowed by the UI -it does not make sense to me.

**Comment by stsewd** [comment] 2023-05-04 19:39
This was solved with https://github.com/readthedocs/readthedocs.org/issues/9335.

**Closed by stsewd** 2023-05-04 19:39 UTC
Labels: Design, Bug, Accepted
