### ISSUE TITLE
Build failing with `/bin/bash: line 1: asdf: command not found`

### ISSUE THREAD

**Issue by apocalyptech** [readthedocs/readthedocs.org#10171] opened 2023-03-21 16:39 UTC
## Details

* Read the Docs project URL: https://readthedocs.org/projects/exordium/
* Build URL (if applicable): https://readthedocs.org/projects/exordium/builds/19855052/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/apocalyptech/

## Expected Result

Build should succeed

## Actual Result

Build is failing with `/bin/bash: line 1: asdf: command not found` -- I've also tried re-building old versions which used to work fine, and they're failing with the same error.  I don't specify `asdf` anywhere in my repo or RTD configs, so I'm not sure where that's coming from.  Let me know if I can provide any more info!

**Comment by thephez** [comment] 2023-03-21 16:43
Ditto, was just opening the same issue! I'll drop the info here since I already typed all of it :smile: 

## Details

* Read the Docs project URL: Multiple including https://readthedocs.org/projects/dash-user-docs/
* Build URL (if applicable):
  * Failed: https://readthedocs.org/projects/dash-user-docs/builds/19855245/
  * Successful: https://readthedocs.org/projects/dash-user-docs/builds/19852825/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/thephez/

## Expected Result

Project builds successfully as usual

## Actual Result

Builds failing today with this error:

```
/bin/bash: line 1: asdf: command not found
```

### Screenshots
Failed build:
![image](https://user-images.githubusercontent.com/8145677/226678537-67941146-79f1-4bb6-97e1-0401fb42b266.png)

Successful build of same commit earlier today:
![image](https://user-images.githubusercontent.com/8145677/226679272-8d264667-8777-4351-8c92-2197a22d47c5.png)

**Comment by NickleDave** [comment] 2023-03-21 16:45
Same :disappointed:
  Failed: https://readthedocs.org/projects/crowsetta/builds/19854975/
  Last successful: https://readthedocs.org/projects/crowsetta/builds/19844422/

**Comment by mrmundt** [comment] 2023-03-21 16:47
(Hi @NickleDave !)
Similar but slightly different issue:
![Screen Shot 2023-03-21 at 10 47 01](https://user-images.githubusercontent.com/55767766/226681867-6ecd8e0c-db5d-48a1-948b-e249aa0abd9a.png)

Failed:https://readthedocs.org/projects/pyomo/builds/19855262/
Last successful: https://readthedocs.org/projects/pyomo/builds/19854787/

**Comment by victorlin** [comment] 2023-03-21 16:58
I was previously using `python.version` in the RTD configuration file and saw the python command not found error. After switching to use `build.tools.python`, I see the `asdf` command not found error.

**Comment by jerryjliu** [comment] 2023-03-21 17:17
> (Hi @NickleDave !) Similar but slightly different issue: ![Screen Shot 2023-03-21 at 10 47 01](https://user-images.githubusercontent.com/55767766/226681867-6ecd8e0c-db5d-48a1-948b-e249aa0abd9a.png)
> 
> Failed:https://readthedocs.org/projects/pyomo/builds/19855262/ Last successful: https://readthedocs.org/projects/pyomo/builds/19854787/

running into this as well https://readthedocs.org/projects/gpt-index/builds/19855695/

**Comment by humitos** [comment] 2023-03-21 17:54
The issue with `asdf` command not found should be solved. Can you confirm, please?

**Comment by apocalyptech** [comment] 2023-03-21 18:02
> The issue with `asdf` command not found should be solved. Can you confirm, please?

Yep, seems to be working for me.  Cheers!  I'll close this out, hopefully that's not premature for anyone.

**Comment by mrmundt** [comment] 2023-03-21 18:04
Not working for the `python not found` commend yet.

**Comment by emmettbutler** [comment] 2023-03-21 18:06
I'm seeing the same "python not found" error https://github.com/readthedocs/readthedocs.org/issues/10171#issuecomment-1478295099

**Comment by ericholscher** [comment] 2023-03-21 18:14
We're rolling back out build server deploy, it should be fixed in ~5 mins.

**Comment by victorlin** [comment] 2023-03-21 18:25
[Confirmed](https://readthedocs.org/projects/nextstrain-augur/builds/19856595/) `python3.7` works now. Appreciate the quick fix!

**Comment by mrmundt** [comment] 2023-03-21 18:27
> This should now be fixed for everyone. Sorry about the issues -- we didn't quite realize the impact it was having on our users. Please let us know if anything isn't working properly now.

We appreciate you, thank you!

**Comment by NickleDave** [comment] 2023-03-21 19:02
@ericholscher @humitos we'd like to thank you for all you're doing building and maintaining ReadTheDocs the only way we know how: with this very niche meme that @mrmundt posted in the [US-RSE](https://github.com/USRSE) Slack
![image](https://user-images.githubusercontent.com/11934090/226714031-1767b30e-7a22-4cb9-85c5-aad09ca239f1.png)

**Closed** 2023-03-21 19:12 UTC
Labels: Bug, Accepted
