### ISSUE TITLE
Scrolling with mousewheel does not work as expected

### ISSUE THREAD

**Issue by DeDu** [readthedocs/readthedocs.org#8560] opened 2021-10-05 09:49 UTC
If I use the mousewhell to scroll on any readthedocs site, the scrolling is very slow.

To demostrate I made a video: https://www.dropbox.com/s/wc67qc30doa5z3g/readthedocs_bug.mp4?dl=0

It seems like if the Navigation bar on the left side is not yet scrolled to the limit, scrolling with the mousewheel does only scroll a little tiny bit. In the video I scroll at the same speed all the time. First down, then up. You can see that it scrolls very slow at the beginning, and as soon as the navigation is scrolled all the way, scrolling gets faster although I do not scroll the wheel faster.

It happens in Chrome Version 94.0.4606.61
Same in Inkognito mode (no Chrome extensions)

Same behaviour on any readthedocs site I encountered.

**Comment by astrojuanlu** [comment] 2021-10-05 13:08
Hi @DeDu, this is a duplicate of https://github.com/readthedocs/sphinx_rtd_theme/issues/1238, which is caused by Chrome bug https://bugs.chromium.org/p/chromium/issues/detail?id=1252415. It should be fixed on newer versions (more info in the comments there), let us know otherwise.

**Closed by astrojuanlu** 2021-10-05 13:08 UTC
