### ISSUE TITLE
Unable to find aiohttp==3.6.2 with bandersnatch docs build

### ISSUE THREAD

**Issue by cooperlees** [readthedocs/readthedocs.org#6832] opened 2020-03-29 20:12 UTC
## Details

* Read the Docs project URL: https://bandersnatch.readthedocs.io/en/latest/
* Read the Docs username (if applicable): cooperlees

## Expected Result

I'm trying to build the latest docs and then a 4.0.0 tagged version for a new release. It's failing as we can not install aiohttp==3.6.2 in the Read The Docs Virtualenv and I am not sure why.

- My doc building CI is passing - example: https://travis-ci.org/github/pypa/bandersnatch/jobs/668469333

## Actual Result
The build fails in the virtualenv setup - Here is the raw log will the failure: https://pastebin.com/nvatW6JC

```
Installed /home/docs/checkouts/readthedocs.org/user_builds/bandersnatch/envs/latest/lib/python3.7/site-packages/aiohttp_xmlrpc-0.8.1-py3.7.egg
error: The 'aiohttp' distribution was not found and is required by aiohttp-xmlrpc, bandersnatch
```

Any tips or things I can do will be appreciated! Thanks for the great service!

**Comment by humitos** [comment] 2020-03-30 05:26
I think it was a temporal issue. I had problems today with PyPI returning 503.

You project builds properly: https://readthedocs.org/projects/bandersnatch/builds/10722631/

**Comment by cooperlees** [comment] 2020-03-30 14:30
Rightio - Thanks - I only opened cause it failed multiple times over different weeks when I tried.

**Comment by cooperlees** [comment] 2020-03-30 14:32
Trying to build 4.0.0 docs just failed too: https://readthedocs.org/projects/bandersnatch/builds/10725803/

**Comment by cooperlees** [comment] 2020-04-01 17:17
Gave it a few days and it failed again for the 4.0.0
https://readthedocs.org/projects/bandersnatch/builds/10744715/

What can we do here? Is there code I can try look at for the bug - Better debug logs? I'd help if I could. Just feel like this needs more admin access and understanding to your infra to debug.

**Comment by humitos** [comment] 2020-04-02 11:18
I think I found the problem.

If you take a look at the output of `python setup.py install`,

a SUCCESS build shows:

```
Installed /home/docs/checkouts/readthedocs.org/user_builds/bandersnatch/envs/3.6.0/lib/python3.7/site-packages/filelock-3.0.12-py3.7.egg
Searching for aiohttp
Reading https://pypi.org/simple/aiohttp/
Downloading https://files.pythonhosted.org/packages/f9/ab/00a073841b7c0b869b0c5c9939fa6aa2e1aac60e0d5ef3e1bc4549c4dd74/aiohttp-4.0.0a1-cp37-cp37m-manylinux1_x86_64.whl#sha256=ea26536ae06df6dac021303a0df72c79e55512070e6a304ba93ad468a3a754dc
Best match: aiohttp 4.0.0a1
Processing aiohttp-4.0.0a1-cp37-cp37m-manylinux1_x86_64.whl
Installing aiohttp-4.0.0a1-cp37-cp37m-manylinux1_x86_64.whl to /home/docs/checkouts/readthedocs.org/user_builds/bandersnatch/envs/3.6.0/lib/python3.7/site-packages
writing requirements to /home/docs/checkouts/readthedocs.org/user_builds/bandersnatch/envs/3.6.0/lib/python3.7/site-packages/aiohttp-4.0.0a1-py3.7-linux-x86_64.egg/EGG-INFO/requires.txt
Adding aiohttp 4.0.0a1 to easy-install.pth file
```

a FAILING build shows:

```
Searching for aiohttp
Downloading https://files.pythonhosted.org/packages/d9/5f/ccf7d8f12e59917fdabbd6b363c9d9863d1f5baac8499093ee7959d91f61/aiohttp-xmlrpc-0.8.1.tar.gz#sha256=b42d453c137077bc4bd1b1ab0c0a9d8b0bda9b9d456af07ecab4647538e42d0f
Best match: aiohttp xmlrpc-0.8.1
Processing aiohttp-xmlrpc-0.8.1.tar.gz
Writing /tmp/easy_install-p84vtocl/aiohttp-xmlrpc-0.8.1/setup.cfg
Running aiohttp-xmlrpc-0.8.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-p84vtocl/aiohttp-xmlrpc-0.8.1/egg-dist-tmp-23l_oa0x
warning: no files found matching '*.xsd' under directory 'aiohttp_xmlrpc'
removing '/home/docs/checkouts/readthedocs.org/user_builds/bandersnatch/envs/4.0.0/lib/python3.7/site-packages/aiohttp_xmlrpc-0.8.1-py3.7.egg' (and everything under it)
creating /home/docs/checkouts/readthedocs.org/user_builds/bandersnatch/envs/4.0.0/lib/python3.7/site-packages/aiohttp_xmlrpc-0.8.1-py3.7.egg
Extracting aiohttp_xmlrpc-0.8.1-py3.7.egg to /home/docs/checkouts/readthedocs.org/user_builds/bandersnatch/envs/4.0.0/lib/python3.7/site-packages
aiohttp-xmlrpc 0.8.1 is already the active version in easy-install.pth
```

So, basically it's installing a different package because it does not find the exact one. I'm not sure why yet, but I wanted to comment this here since maybe you have a clue.

**Comment by humitos** [comment] 2020-04-02 11:27
The problem is not RTD related, though. There is something wrong with your package.

```
$ git clone git@github.com:pypa/bandersnatch.git
Cloning into 'bandersnatch'...
remote: Enumerating objects: 57, done.
remote: Counting objects: 100% (57/57), done.
remote: Compressing objects: 100% (44/44), done.
remote: Total 4395 (delta 19), reused 27 (delta 12), pack-reused 4338
Receiving objects: 100% (4395/4395), 815.20 KiB | 1.69 MiB/s, done.
Resolving deltas: 100% (2814/2814), done.
Time: 0h:00m:03s                                                                                                                                                                                             

/tmp ⌚ 13:23:45
$ python -m venv env ; source env/bin/activate
(env) 
/tmp ⌚ 13:23:54
$ cd bandersnatch 
(env) 
/tmp/bandersnatch on  master ⌚ 13:24:02
$ python setup.py install

...

Installed /tmp/env/lib/python3.8/site-packages/filelock-3.0.12-py3.8.egg
Searching for aiohttp-xmlrpc
Reading https://pypi.org/simple/aiohttp-xmlrpc/
Downloading https://files.pythonhosted.org/packages/0d/d0/4c6af6bdbcc4fae1bb63d8e5f47608890939088b59e712836f320e1577e1/aiohttp_xmlrpc-0.8.1-py3-none-any.whl#sha256=a28bc5f16a39766860d985467d25e865290c7a3b4c94bc779c8cb5167183e52e
Best match: aiohttp-xmlrpc 0.8.1
Processing aiohttp_xmlrpc-0.8.1-py3-none-any.whl
Installing aiohttp_xmlrpc-0.8.1-py3-none-any.whl to /tmp/env/lib/python3.8/site-packages
writing requirements to /tmp/env/lib/python3.8/site-packages/aiohttp_xmlrpc-0.8.1-py3.8.egg/EGG-INFO/requires.txt
Adding aiohttp-xmlrpc 0.8.1 to easy-install.pth file

Installed /tmp/env/lib/python3.8/site-packages/aiohttp_xmlrpc-0.8.1-py3.8.egg
Searching for aiohttp
Downloading https://files.pythonhosted.org/packages/d9/5f/ccf7d8f12e59917fdabbd6b363c9d9863d1f5baac8499093ee7959d91f61/aiohttp-xmlrpc-0.8.1.tar.gz#sha256=b42d453c137077bc4bd1b1ab0c0a9d8b0bda9b9d456af07ecab4647538e42d0f
Best match: aiohttp xmlrpc-0.8.1
Processing aiohttp-xmlrpc-0.8.1.tar.gz
Writing /tmp/easy_install-ivx_9rsj/aiohttp-xmlrpc-0.8.1/setup.cfg
Running aiohttp-xmlrpc-0.8.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-ivx_9rsj/aiohttp-xmlrpc-0.8.1/egg-dist-tmp-q8e24501
warning: no files found matching '*.xsd' under directory 'aiohttp_xmlrpc'
removing '/tmp/env/lib/python3.8/site-packages/aiohttp_xmlrpc-0.8.1-py3.8.egg' (and everything under it)
creating /tmp/env/lib/python3.8/site-packages/aiohttp_xmlrpc-0.8.1-py3.8.egg
Extracting aiohttp_xmlrpc-0.8.1-py3.8.egg to /tmp/env/lib/python3.8/site-packages
aiohttp-xmlrpc 0.8.1 is already the active version in easy-install.pth

Installed /tmp/env/lib/python3.8/site-packages/aiohttp_xmlrpc-0.8.1-py3.8.egg
error: The 'aiohttp' distribution was not found and is required by bandersnatch, aiohttp-xmlrpc
Time: 0h:00m:06s                                                                                                                                                                                             
(env) 
/tmp/bandersnatch on  master ⌚ 13:24:12
$ 
```

I'm closing it, but feel free to reopen if you think there is something we can do from our side.

BTW, you may not need to install all the dependencies of your package just to build the docs. You can create a `[docs]` section in your `setup.cfg` file and call tell Read the Docs to install those dependencies only: https://docs.readthedocs.io/en/stable/config-file/v2.html#packages

**Closed by humitos** 2020-04-02 11:27 UTC
