### ISSUE TITLE
Build: `build.jobs.post_build` produces mysterious shell syntax errors

### ISSUE THREAD

**Issue by rptb1** [readthedocs/readthedocs.org#10103] opened 2023-03-04 05:09 UTC
## Details

* Read the Docs project URL: https://readthedocs.org/projects/mmref/
* Build URL (if applicable): https://readthedocs.org/projects/mmref/builds/19671469/ and https://readthedocs.org/projects/mmref/builds/19671433/ and most previous  builds
* Read the Docs username (if applicable): https://readthedocs.org/profiles/rptb1/

## Expected Result

A post_build script `if test -n "A"; then echo "B"; fi` should not produce a syntax error.
A post_build script with `sh -c "foo"` in it should run the shell with the argument.

## Actual Result

`/bin/sh: 1: Syntax error: "then" unexpected`
`sh: 0: -c requires an argument`

I'm following the manual at ["Extend the build process"](https://docs.readthedocs.io/en/stable/build-customization.html#extend-the-build-process) and trying to insert a simple shell script at the post_build step.

A script that works locally (Ubuntu 22) is somehow mangled and causes syntax errors when inserted into the .readthedocs.yml at the post_build stage.  I have tried many ways of writing the script and quoting it in YAML, to try to eliminate YAML as the culprit:

1. https://github.com/Ravenbrook/mps/pull/187/commits/4146715a1253a9ba7dcb8e528997545d52bb7ab2
2. https://github.com/Ravenbrook/mps/pull/187/commits/9fbc6224dbe1b645568fd32a938c77f84ef67d3a
3. https://github.com/Ravenbrook/mps/pull/187/commits/2a642594a525a3cbcd0d9c10f686bf6b6e43307c
4. https://github.com/Ravenbrook/mps/pull/187/commits/7fdbbd3ff01544484ba5a518b46c96dc9c98f1f3
5. https://github.com/Ravenbrook/mps/pull/187/commits/82f0d180a1bb0a7909d94eee22ab4a7b71a7dea3
6. https://github.com/Ravenbrook/mps/pull/187/commits/044e790f24217ad709dbc8ced9c35febaf02f0e9
7. https://github.com/Ravenbrook/mps/pull/187/commits/4a07b8418a4e5b1036dd50f13552098308972fb2
8. https://github.com/Ravenbrook/mps/pull/187/commits/1106c9cd066c9638ccf2f7772083384bb526673f

The [last one](https://github.com/Ravenbrook/mps/pull/187/commits/1106c9cd066c9638ccf2f7772083384bb526673f) is especially mysterious.

Is there some sort of mangling of the script going on, or am I just going blind?

None of these scripts produce syntax errors when I feed them to /bin/sh on my local Ubuntu.  I have written similar scripts for multiple CI systems without coming across this problem before.

Thanks.

**Comment by rptb1** [comment] 2023-03-04 05:29
A *literal copy of your own example* produces a syntax error.

I coped the text of the script from https://docs.readthedocs.io/en/stable/build-customization.html#id3 in exactly in https://github.com/Ravenbrook/mps/pull/187/commits/b08bcf32bcd8d0e38e3e4bcc474820c16eda53e6 and it causes the syntax error seen at https://readthedocs.org/projects/mmref/builds/19671564/

**Comment by humitos** [comment] 2023-03-06 08:34
Thanks for reporting this issue. We have been dealing with this already at https://github.com/pypi/warehouse/pull/12953 and I wasn't able to find the cause of it at that time. We will need to dig deeper into the code to understand what's going on here.

**Comment by rptb1** [comment] 2023-03-06 20:22
> We will need to dig deeper into the code to understand what's going on here.

This split looks highly suspicious. https://github.com/readthedocs/readthedocs.org/blob/f4215c5516eaa07c15afe49abdf1bb7a1a34655a/readthedocs/doc_builder/director.py#L333

From a 10 minute scan of your code, it looks to me like there might be a confusion between executing a single command and executing a script.

On a single command, where you want to split argv and do something like `run(['ls', '-l'])`, because you're basically doing something like a call to [exec(3)](https://linux.die.net/man/3/exec) and spawing a single process.

But a *script* is a single string that you want to pass *complete* to a shell, like `run(['/bin/sh', '-c', SCRIPT])` (or similar).  Splitting the script makes no sense at all.

```
>>> post_build = """
... if test -n "${MMREF}"; then \
...          mv "${READTHEDOCS_OUTPUT}/html" "${READTHEDOCS_OUTPUT}/mmref.in" && \
...          python manual/make-mmref.py "${READTHEDOCS_OUTPUT}/mmref.in" "${READTHEDOCS_OUTPUT}/html" \
...     fi
... """
>>> post_build.split()
['if', 'test', '-n', '"${MMREF}";', 'then', 'mv', '"${READTHEDOCS_OUTPUT}/html"', '"${READTHEDOCS_OUTPUT}/mmref.in"', '&&', 'python', 'manual/make-mmref.py', '"${READTHEDOCS_OUTPUT}/mmref.in"', '"${READTHEDOCS_OUTPUT}/html"', 'fi']
```

Again, I am in no way sure this is what's wrong, but your splits don't look right to me.

**Comment by ericholscher** [comment] 2023-03-07 15:16
@rptb1 I'm curious if it works if you put the script in a file, and just run that from the post-build step? Not ideal, but I don't think our indention with this feature was having full-length scripts here, but having commands or scripts that could be run. We can definitely change that design, but curious if it works that way.

**Comment by humitos** [comment] 2023-03-09 09:44
I'm re-opening this issue because the PR that was merged doesn't solve all the issues.
I'm still not sure what's the best way to solve this problem 🤷🏼 . This case, for example, is not solved:

![Screenshot_2023-03-09_10-41-14](https://user-images.githubusercontent.com/244656/223982456-2a45cb79-43da-47a4-a545-355440b9b7df.png)

That exact same code works properly in my local terminal. Even wrapping it in `/bin/sh -c '{cmd}'` as we are doing in our code. It seems we are doing some manipulation of the command that breaks it, or, there is a problem when communicating with Docker.

This requires more researching and testing. Suggestions and ideas welcomed!

**Comment by humitos** [comment] 2023-03-09 09:51
Another simplified example that breaks because of the environment variable prefix:

```
▶ sh -c 'if [ "1" ]; then echo 1; fi'
1

▶ sh -c 'FOO=bar if [ "1" ]; then echo 1; fi'
sh: -c: line 1: syntax error near unexpected token `then'
sh: -c: line 1: `FOO=bar if [ "1" ]; then echo 1; fi'
```

**Comment by humitos** [comment] 2023-03-09 10:54
I opened 2 PRs to solve this issue:

* #10133 moves all the environment variable management to the Docker `create_exec` call
* https://github.com/readthedocs/readthedocs-docker-images/pull/189 updates `asdf` in our Docker images to auto reshim executables installed via `pip`

With these two, I think we will be solving most of our users' issues avoiding unexpected behaviors.

**Comment by ericholscher** [comment] 2023-03-09 17:42
@humitos Great work tracking this down!

**Comment by humitos** [comment] 2023-03-29 09:58
We deployed a fix twice for this but we had other issues, so we had to roll them back. I'm re-opening this issue because the problem is not fixed in production.

**Comment by bensze01** [comment] 2023-05-11 13:16
So, I've run into this issue as well (Mbed-TLS/mbedtls#7538) - The workaround I settled on is to insert a newline before the `if` statement.
However reading through @humitos's explanation, this probably breaks makes the `PATH=` statement ineffective.
I guess if passing this variable to docker had to be rolled back, you could make the commands look like this instead
```
export PATH=${foo}
${command_from_yaml}
````

**Closed** 2023-05-23 04:12 UTC
Labels: Bug, Accepted
